openapi: 3.0.2
info:
  contact:
    email: devnet@cisco.com
    name: Cisco DevNet
    url: https://developer.cisco.com/
  description: Unified OpenAPI spec for Cisco Secure Access APIs.
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Cisco Secure Access API
  version: v2.0.202510221109
servers:
- url: https://api.sse.cisco.com
- url: https://api.sse.cisco.com/{basePath}
  variables:
    basePath:
      default: deployments/v2
security:
- http: []
- oauthFlow: []
tags:
- name: Internal Networks
- description: API Usage reports
  name: API Usage Report
- name: Applications
- name: Application Categories
- name: Protocols
- name: Identities
- description: Manage the application lists and the internet destinations in the application
    lists.
  name: Application Lists
- description: The Content Category settings.
  name: Content Categories
- description: Destination Lists
  name: Destination Lists
- description: Destinations
  name: Destinations
- name: DNS Forwarders
- name: Internal Domains
- name: Domain Status and Categorization
- name: Domain Volume
- name: Co-occurrences for a Domain
- name: Passive DNS
- name: Tagging Timeline
- name: Subdomains for a Domain
- name: Related Domains for a Domain
- name: Security Information for a Domain
- name: AS Information for a Domain
- name: WHOIS Information for a Domain
- name: Popularity List-Top Million Domains
- name: Search Domain
- name: Cisco Secure Malware Analytics Integration
- description: The IPS profiles with signatures.
  name: IPS Profiles
- name: API Keys
- name: Usage Metrics
- description: Manage the Network Objects in the organization.
  name: Network Objects
- description: Manage the Network Object Groups in the organization.
  name: Network Object Groups
- description: Manage the Service Objects in the organization.
  name: Service Objects
- description: Manage the Service Object Groups in the organization.
  name: Service Object Groups
- description: List the Objects and Object Groups in the organization.
  name: Unified Objects
- description: Secure Access Network Device Management
  name: Network Devices
- description: Network Tunnel Groups API endpoints
  name: Network Tunnel Groups
- description: Network Tunnel Groups Regions API endpoints
  name: Network Tunnel Groups Regions
- description: Network Tunnel Groups State API endpoints
  name: Network Tunnel Groups State
- description: Network Tunnel Groups Peer State API endpoints
  name: Network Tunnel Groups Peer State
- name: Networks
- description: The API endpoints that manage the access rules for the organization.
  name: Access Rules
- description: The API endpoints that manage the rule settings and defaults on the
    access rules.
  name: Rule Settings and Defaults
- description: The Secure Access Private Resource Groups
  name: Resource Groups
- description: The Secure Access Private Resources
  name: Private Resources
- name: Activity
- name: Top Identities
- name: Identity Distribution
- name: Top Resources
- name: Top Destinations
- name: Top Categories
- name: Top Event Types
- name: Top DNS Query Types
- name: Organization Requests by Hour
- name: Organization Requests by Timerange
- name: Organization Requests by Hour and Category
- name: Organization Requests by Timerange and Category
- name: Deployment Status
- name: Bandwidth by Hour
- name: Bandwidth by Timerange
- name: Top Files
- name: Total Requests
- name: Top Threats
- name: Top Threat Types
- name: Utility
- name: Top IPs
- name: Summary
- name: Summaries by Category
- name: Summaries by Destination
- name: Summaries by Rule
- name: Remote Access
- name: Private Resource
- name: Requests Resource Connector
- name: Requests Summary Resource Connector Groups
- name: Resource Connectors
- name: Rules Activity
- name: Unique Resources
- description: Manage the Resource Connector Groups.
  name: Connector Groups
- description: Manage the Resource Connectors.
  name: Connectors
- name: Roaming Computers
- name: Organization Information
- name: S3 Bucket Key Rotation
- description: The Security profiles in the organization.
  name: Security Profiles
- name: Sites
- description: The Tenant Controls Profiles settings.
  name: Tenant Controls Profiles
- description: Integration management
  name: Integrations
- description: Credential management
  name: Credentials
- description: Integration types
  name: Integration Types
- description: Manage the threat feeds for the third-party and custom security vendors.
  name: Feeds
- name: Token
- name: VPN Sessions
- name: ACME Client Certificates
paths:
  /admin/v2/apiKeys:
    get:
      description: List the API keys created by your organization.
      operationId: getAPIKeys
      security:
      - oauthFlow:
        - admin.apikeys:read
      summary: List API Keys
      tags:
      - API Keys
    post:
      description: 'Create an API key with certain scopes, name, description, allowed
        IP addresses and CIDR blocks, and expiration.

        The `description` and `allowedIPs` fields are optional.'
      operationId: createAPIKeys
      security:
      - oauthFlow:
        - admin.apikeys:create
      summary: Create API Key
      tags:
      - API Keys
  /admin/v2/apiKeys/{apiKeyId}:
    delete:
      description: Delete an API key.
      operationId: deleteAPIKey
      security:
      - oauthFlow:
        - admin.apikeys:delete
      summary: Delete API Key
      tags:
      - API Keys
    get:
      description: Get an API key.
      operationId: getAPIKey
      security:
      - oauthFlow:
        - admin.apikeys:read
      summary: Get API Key
      tags:
      - API Keys
    patch:
      description: 'Set new values for the name, description, scopes, or allowed IPs
        for an API key.

        The system does not accept the same value for the properties of the API key.'
      operationId: patchAPIKey
      security:
      - oauthFlow:
        - admin.apikeys:update
      summary: Update API Key
      tags:
      - API Keys
  /admin/v2/apiKeys/{apiKeyId}/refresh:
    post:
      description: Refresh the API key and secret.
      operationId: refreshApiKey
      security:
      - oauthFlow:
        - admin.apikeys:refresh
      summary: Refresh API Key
      tags:
      - API Keys
  /admin/v2/iam/rotateKey:
    post:
      description: Rotate the Cisco-managed S3 bucket key for the organization.
      operationId: createS3BucketKey
      security:
      - oauthFlow:
        - admin.iam:write
      summary: Refresh S3 Bucket Key
      tags:
      - S3 Bucket Key Rotation
  /admin/v2/integrationTypes:
    get:
      description: List the types of the third-party applications integrated in the
        organization.
      operationId: getIntegrationTypes
      security:
      - oauthFlow:
        - admin.integrations:read
      summary: List Types of Integrations
      tags:
      - Integration Types
  /admin/v2/integrations:
    get:
      description: List the third-party applications integrated in the organization.
        Filter the collection by `type` and `status`.
      operationId: getIntegrations
      security:
      - oauthFlow:
        - admin.integrations:read
      summary: List Integrations
      tags:
      - Integrations
    post:
      description: Create a third-party integration in the organization.
      operationId: createIntegration
      security:
      - oauthFlow:
        - admin.integrations:write
      summary: Create Integration
      tags:
      - Integrations
  /admin/v2/integrations/{intId}:
    delete:
      description: Delete an integration in the organization.
      operationId: deleteIntegration
      security:
      - oauthFlow:
        - admin.integrations:write
      summary: Delete Integration
      tags:
      - Integrations
    get:
      description: Get an integration by ID.
      operationId: getIntegration
      security:
      - oauthFlow:
        - admin.integrations:read
      summary: Get Integration
      tags:
      - Integrations
    patch:
      description: Update an integration in the organization.
      operationId: updateIntegration
      security:
      - oauthFlow:
        - admin.integrations:write
      summary: Update Integration
      tags:
      - Integrations
  /admin/v2/integrations/{intId}/credentials:
    post:
      description: Create the credentials for a third-party application integrated
        in the organization.
      operationId: createCredentialsForIntegration
      security:
      - oauthFlow:
        - admin.integrations:write
      summary: Create Credentials for Integration
      tags:
      - Credentials
  /admin/v2/integrations/{intId}/credentials/{credId}:
    get:
      description: Get the credentials by ID for an integration.
      operationId: getCredentialsForIntegration
      security:
      - oauthFlow:
        - admin.integrations:read
      summary: Get Credentials for Integration
      tags:
      - Credentials
  /admin/v2/integrations/{intId}/credentials/{credId}/value:
    get:
      description: Get the value of the credentials for the integration.
      operationId: getCredentialsforIntegration
      security:
      - oauthFlow:
        - admin.integrations:read
      summary: Get Value of Credentials for Integration
      tags:
      - Credentials
  /admin/v2/vpn/userConnections:
    get:
      description: List the VPN sessions created by your organization.
      operationId: getVpnSessions
      security:
      - oauthFlow:
        - admin.vpn:read
      summary: List VPN Connections
      tags:
      - VPN Sessions
    put:
      description: Disconnect the remote VPN sessions.
      operationId: updateVpnConnections
      security:
      - oauthFlow:
        - admin.vpn:write
      summary: Disconnect VPN Users
      tags:
      - VPN Sessions
  /admin/v2/ztna/userSummaries:
    get:
      description: Get the status and counts of device certificates for the zero trust
        users.
      operationId: getCountsZtaDeviceCertificates
      security:
      - oauthFlow:
        - admin.ztna.users:read
      summary: Get Counts Device Certificates
      tags:
      - ACME Client Certificates
  /admin/v2/ztna/users/{userId}/deviceCertificates:
    get:
      description: Get the latest ACME-issued device certificates for the zero trust
        user.
      operationId: getZtaAllDeviceCertificates
      security:
      - oauthFlow:
        - admin.ztna.certificates:read
      summary: List Certificates for User
      tags:
      - ACME Client Certificates
  /admin/v2/ztna/users/{userId}/devices/{deviceId}:
    delete:
      description: Revoke active ACME-issued certificates and remove the zero trust
        user device.
      operationId: deleteZtaDeviceCertificates
      security:
      - oauthFlow:
        - admin.ztna.enrollment:write
      summary: Revoke Certificates for Device
      tags:
      - ACME Client Certificates
  /admin/v2/ztna/users/{userId}/devices/{deviceId}/certificates:
    get:
      description: Get the latest ACME-issued certificate for the zero trust user
        and device.
      operationId: getZtaDeviceCertificates
      security:
      - oauthFlow:
        - admin.ztna.devices:read
      summary: List Certificates for Device
      tags:
      - ACME Client Certificates
  /auth/v2/token:
    post:
      description: Create an authorization token.
      operationId: createAuthToken
      summary: Create Authorization Token
      tags:
      - Token
  /deployments/v2/connectorAgents:
    get:
      description: 'List the Connectors for the Resouce Connector Groups in the organization.

        If you include query filters on the request, the response is a subset of the
        Connectors in the organization.'
      operationId: listConnectors
      security:
      - oauthFlow:
        - deployments.resourceconnectors:read
      summary: List Connectors
      tags:
      - Connectors
  /deployments/v2/connectorAgents/{id}:
    delete:
      description: Remove the Connector from the Resource Connector Group in the organization.
      operationId: deleteConnector
      security:
      - oauthFlow:
        - deployments.resourceconnectors:write
      summary: Delete Connector
      tags:
      - Connectors
    get:
      description: Get the details about a Connector.
      operationId: getConnector
      security:
      - oauthFlow:
        - deployments.resourceconnectors:read
      summary: Get Connector
      tags:
      - Connectors
    patch:
      description: Update the properties on the Connector.
      operationId: patchConnector
      security:
      - oauthFlow:
        - deployments.resourceconnectors:write
      summary: Patch Connector
      tags:
      - Connectors
  /deployments/v2/connectorAgents/counts:
    get:
      description: Get the counts of the state information for the Connectors.
      operationId: getConnectorAgentCount
      security:
      - oauthFlow:
        - deployments.resourceconnectors:read
      summary: Get Counts Connectors States
      tags:
      - Connectors
  /deployments/v2/connectorGroups:
    get:
      description: 'List the Resource Connector Groups in the organization.

        If you include `filters` on the request, the response is a subset of the Resource
        Connector Groups in the organization.'
      operationId: listConnectorGroups
      security:
      - oauthFlow:
        - deployments.resourceconnectors:read
      summary: List Resource Connector Groups
      tags:
      - Connector Groups
    post:
      description: Create a Resource Connector Group in the organization.
      operationId: createConnectorGroup
      security:
      - oauthFlow:
        - deployments.resourceconnectors:write
      summary: Create Resource Connector Group
      tags:
      - Connector Groups
  /deployments/v2/connectorGroups/{id}:
    delete:
      description: Delete the Resouce Connector Group, including the Connectors in
        the Resource Connector Group.
      operationId: deleteConnectorGroup
      security:
      - oauthFlow:
        - deployments.resourceconnectors:write
      summary: Delete Resource Connector Group
      tags:
      - Connector Groups
    get:
      description: Get the details about a Resource Connector Group.
      operationId: getConnectorGroup
      security:
      - oauthFlow:
        - deployments.resourceconnectors:read
      summary: Get Resource Connector Group
      tags:
      - Connector Groups
    patch:
      description: 'Update the `name` or `location` properties on the Resource Connector
        Group, or

        refresh the Resource Connector Group''s provisioning key.'
      operationId: patchConnectorGroup
      security:
      - oauthFlow:
        - deployments.resourceconnectors:write
      summary: Patch Resource Connector Group
      tags:
      - Connector Groups
    put:
      description: Update the `name` and `location` properties on the Resource Connector
        Group.
      operationId: putConnectorGroup
      security:
      - oauthFlow:
        - deployments.resourceconnectors:write
      summary: Update Resource Connector Group
      tags:
      - Connector Groups
  /deployments/v2/connectorGroups/counts:
    get:
      description: Get the counts of the state information for the Resource Connector
        Groups.
      operationId: getConnectorGroupCount
      security:
      - oauthFlow:
        - deployments.resourceconnectors:read
      summary: Get Counts Resource Connector Groups States
      tags:
      - Connector Groups
  /deployments/v2/dnsForwarders:
    get:
      description: List the DNS Forwarders in the organization.
      operationId: listDnsForwarders
      security:
      - oauthFlow:
        - deployments.dnsforwarders:read
      summary: List DNS Forwarders
      tags:
      - DNS Forwarders
    post:
      description: Add a DNS Forwarder in the organization.
      operationId: createDnsForwarder
      security:
      - oauthFlow:
        - deployments.dnsforwarders:write
      summary: Create DNS Forwarder
      tags:
      - DNS Forwarders
  /deployments/v2/dnsForwarders/{dnsForwardersId}:
    delete:
      description: Remove the registered DNS Forwarder in the organization.
      operationId: deleteDnsForwarder
      security:
      - oauthFlow:
        - deployments.dnsforwarders:write
      summary: Delete DNS Forwarder
      tags:
      - DNS Forwarders
    get:
      description: Get the properties for a DNS Forwarder.
      operationId: getDnsForwarder
      security:
      - oauthFlow:
        - deployments.dnsforwarders:read
      summary: Get DNS Forwarder
      tags:
      - DNS Forwarders
    put:
      description: Update the properties of a DNS Forwarder.
      operationId: updateDnsForwarder
      security:
      - oauthFlow:
        - deployments.dnsforwarders:write
      summary: Update DNS Forwarder
      tags:
      - DNS Forwarders
  /deployments/v2/identities/registrations/{type}:
    get:
      description: Get the list of identity endpoints or security group tags (SGTs)
        for the identities in the organization.
      operationId: getIdentities
      security:
      - oauthFlow:
        - deployments.identities:read
      summary: List Identities
      tags:
      - Identities
    put:
      description: "* Use the `PUT` operation to add a list of identity devices or\
        \ security group tags (SGTs) in the organization. For each API operation,\
        \ you can add 1\u2013250 identity devices\n  or security group tags.\n* Use\
        \ the `PUT` operation to modify the properties of the identities registered\
        \ in the organization.\n  When you set the `status` field of an identity endpoint\
        \ or security group tag to `inactive`, Secure Access makes the identity inactive\
        \ in the organization\n  and the identity is not managed or protected by the\
        \ configured access rules and security controls in the Access policy."
      operationId: updateIdentities
      security:
      - oauthFlow:
        - deployments.identities:write
      summary: Update Identities
      tags:
      - Identities
  /deployments/v2/internaldomains:
    get:
      description: List the internal domains.
      operationId: listInternalDomains
      security:
      - oauthFlow:
        - deployments.internaldomains:read
      summary: List Internal Domains
      tags:
      - Internal Domains
    post:
      description: 'Create an internal domain. If you do not assign a list of sites
        to the internal domain, the internal domain

        is associated with all sites in the organization.'
      operationId: createInternalDomain
      security:
      - oauthFlow:
        - deployments.internaldomains:write
      summary: Create Internal Domain
      tags:
      - Internal Domains
  /deployments/v2/internaldomains/{internalDomainId}:
    delete:
      description: Delete an internal domain.
      operationId: deleteInternalDomain
      security:
      - oauthFlow:
        - deployments.internaldomains:write
      summary: Delete Internal Domain
      tags:
      - Internal Domains
    get:
      description: Get an internal domain.
      operationId: getInternalDomain
      security:
      - oauthFlow:
        - deployments.internaldomains:read
      summary: Get Internal Domain
      tags:
      - Internal Domains
    put:
      description: Update an internal domain.
      operationId: updateInternalDomain
      security:
      - oauthFlow:
        - deployments.internaldomains:write
      summary: Update Internal Domain
      tags:
      - Internal Domains
  /deployments/v2/internalnetworks:
    get:
      description: List the internal networks.
      operationId: listInternalNetworks
      security:
      - oauthFlow:
        - deployments.internalnetworks:read
      summary: List Internal Networks
      tags:
      - Internal Networks
    post:
      description: Create an internal network.
      operationId: createInternalNetwork
      security:
      - oauthFlow:
        - deployments.internalnetworks:write
      summary: Create Internal Network
      tags:
      - Internal Networks
  /deployments/v2/internalnetworks/{internalNetworkId}:
    delete:
      description: Delete an internal network.
      operationId: deleteInternalNetwork
      security:
      - oauthFlow:
        - deployments.internalnetworks:write
      summary: Delete Internal Network
      tags:
      - Internal Networks
    get:
      description: Get an internal network.
      operationId: getInternalNetwork
      security:
      - oauthFlow:
        - deployments.internalnetworks:read
      summary: Get Internal Network
      tags:
      - Internal Networks
    put:
      description: Update an internal network.
      operationId: updateInternalNetwork
      security:
      - oauthFlow:
        - deployments.internalnetworks:write
      summary: Update Internal Network
      tags:
      - Internal Networks
  /deployments/v2/networkdevices:
    get:
      description: List the network devices.
      operationId: getAllNetworkDevices
      security:
      - oauthFlow:
        - deployments.networkdevices:read
      summary: List Network Devices
      tags:
      - Network Devices
    post:
      description: Create a network device.
      operationId: createNetworkDevice
      security:
      - oauthFlow:
        - deployments.networkdevices:write
      summary: Create Network Device
      tags:
      - Network Devices
  /deployments/v2/networkdevices/{originId}:
    delete:
      description: Remove a network device.
      operationId: deleteNetworkDevice
      security:
      - oauthFlow:
        - deployments.networkdevices:write
      summary: Delete Network Device
      tags:
      - Network Devices
    get:
      description: Get a network device.
      operationId: getNetworkDevice
      security:
      - oauthFlow:
        - deployments.networkdevices:read
      summary: Get Network Device
      tags:
      - Network Devices
    patch:
      description: Update a network device.
      operationId: updateNetworkDevice
      security:
      - oauthFlow:
        - deployments.networkdevices:write
      summary: Update Network Device
      tags:
      - Network Devices
  /deployments/v2/networks:
    get:
      description: List the Networks in the organization.
      operationId: listNetworks
      security:
      - oauthFlow:
        - deployments.networks:read
      summary: List Networks
      tags:
      - Networks
    post:
      description: Create a network. Before you can create a network, contact Support
        to get your IP range verified.
      operationId: createNetwork
      security:
      - oauthFlow:
        - deployments.networks:write
      summary: Create Network
      tags:
      - Networks
  /deployments/v2/networks/{networkId}:
    delete:
      description: Delete a network registered in the organization.
      operationId: deleteNetwork
      security:
      - oauthFlow:
        - deployments.networks:write
      summary: Delete Network
      tags:
      - Networks
    get:
      description: Get a Network registered in the organization.
      operationId: getNetwork
      security:
      - oauthFlow:
        - deployments.networks:read
      summary: Get Network
      tags:
      - Networks
    put:
      description: Update a Network. Before you can update the network's IP address,
        contact Support to get your IP range verified.
      operationId: updateNetwork
      security:
      - oauthFlow:
        - deployments.networks:write
      summary: Update Network
      tags:
      - Networks
  /deployments/v2/networktunnelgroups:
    get:
      description: 'List the Network Tunnel Groups in the organization.

        If you enable the `includeStatuses` query parameter in your API request,

        the response includes the `tunnelsStatus` field.

        The maximum number of items in a hub''s list of tunnel states (`tunnelsStatus`)
        is 10.'
      operationId: listNetworkTunnelGroups
      security:
      - oauthFlow:
        - deployments.networktunnelgroups:read
      summary: List Network Tunnel Groups
      tags:
      - Network Tunnel Groups
    post:
      description: Create a Network Tunnel Group in the organization.
      operationId: addNetworkTunnelGroup
      security:
      - oauthFlow:
        - deployments.networktunnelgroups:write
      summary: Create Network Tunnel Group
      tags:
      - Network Tunnel Groups
  /deployments/v2/networktunnelgroups/{id}:
    delete:
      description: Delete a Network Tunnel Group in the organization.
      operationId: deleteNetworkTunnelGroup
      security:
      - oauthFlow:
        - deployments.networktunnelgroups:write
      summary: Delete Network Tunnel Group
      tags:
      - Network Tunnel Groups
    get:
      description: Get a Network Tunnel Group in the organization.
      operationId: getNetworkTunnelGroup
      security:
      - oauthFlow:
        - deployments.networktunnelgroups:read
      summary: Get Network Tunnel Group
      tags:
      - Network Tunnel Groups
    patch:
      description: Update a Network Tunnel Group in the organization.
      operationId: patchNetworkTunnelGroup
      security:
      - oauthFlow:
        - deployments.networktunnelgroups:write
      summary: Update Network Tunnel Group
      tags:
      - Network Tunnel Groups
  /deployments/v2/networktunnelgroups/{id}/networktunnelhubs/{hub_id}/peers/{peer_id}/state:
    get:
      description: Get the state of a peer (tunnel) within an organization's Network
        Tunnel Group and Hub.
      operationId: getPeerState
      security:
      - oauthFlow:
        - deployments.networktunnelgroups:read
      summary: Get Tunnel State
      tags:
      - Network Tunnel Groups Peer State
  /deployments/v2/networktunnelgroups/{id}/peers:
    get:
      description: Get the state of all peers (tunnels) within an organization's Network
        Tunnel Group and Hub.
      operationId: getPeersState
      security:
      - oauthFlow:
        - deployments.networktunnelgroups:read
      summary: Get Tunnel States for Peers
      tags:
      - Network Tunnel Groups Peer State
  /deployments/v2/networktunnelgroups/{id}/state:
    get:
      description: 'Get the status information for the Network Tunnel Group in the
        organization.

        The maximum number of items in a hub''s list of tunnel states (`tunnelsStatus`)
        is 10.'
      operationId: getNetworkTunnelGroupState
      security:
      - oauthFlow:
        - deployments.networktunnelgroups:read
      summary: Get State of Network Tunnel Group
      tags:
      - Network Tunnel Groups State
  /deployments/v2/networktunnelgroupsstate:
    get:
      description: 'Get the state for each Network Tunnel Group in the organization.

        The maximum number of items in a hub''s list of tunnel states (`tunnelsStatus`)
        is 10.'
      operationId: getNetworkTunnelGroupBulkState
      security:
      - oauthFlow:
        - deployments.networktunnelgroups:read
      summary: List State of Network Tunnel Groups
      tags:
      - Network Tunnel Groups State
  /deployments/v2/regions:
    get:
      description: List the available regions for the Network Tunnel Groups.
      operationId: listNetworkTunnelGroupRegions
      security:
      - oauthFlow:
        - deployments.regions:read
      summary: List Regions for Network Tunnel Groups
      tags:
      - Network Tunnel Groups Regions
  /deployments/v2/roamingcomputers:
    get:
      description: List the roaming computers.
      operationId: listRoamingComputers
      security:
      - oauthFlow:
        - deployments.roamingcomputers:read
      summary: List Roaming Computers
      tags:
      - Roaming Computers
  /deployments/v2/roamingcomputers/{deviceId}:
    delete:
      description: Delete a roaming computer in the organization.
      operationId: deleteRoamingComputer
      security:
      - oauthFlow:
        - deployments.roamingcomputers:write
      summary: Delete Roaming Computer
      tags:
      - Roaming Computers
    get:
      description: Get a roaming computer in the organization.
      operationId: getRoamingComputer
      security:
      - oauthFlow:
        - deployments.roamingcomputers:read
      summary: Get Roaming Computer
      tags:
      - Roaming Computers
    put:
      description: Update a roaming computer in the organization.
      operationId: updateRoamingComputer
      security:
      - oauthFlow:
        - deployments.roamingcomputers:write
      summary: Update Roaming Computer
      tags:
      - Roaming Computers
  /deployments/v2/roamingcomputers/orgInfo:
    get:
      description: 'Get the OrgInfo.json properties for deploying the Cisco Secure
        Client on user devices in the organization.

        The Cisco Secure Client with the Internet Security module requires the OrgInfo.json
        properties.'
      operationId: getOrganizationInfo
      security:
      - oauthFlow:
        - deployments.roamingcomputersOrgInfo:read
      summary: Get OrgInfo Properties
      tags:
      - Organization Information
  /deployments/v2/sites:
    get:
      description: List the Sites in the organization.
      operationId: listSites
      security:
      - oauthFlow:
        - deployments.sites:read
      summary: List Sites
      tags:
      - Sites
    post:
      description: Create a Site in the organization.
      operationId: createSite
      security:
      - oauthFlow:
        - deployments.sites:write
      summary: Create Site
      tags:
      - Sites
  /deployments/v2/sites/{siteId}:
    delete:
      description: Delete a Site in the organization.
      operationId: deleteSite
      security:
      - oauthFlow:
        - deployments.sites:write
      summary: Delete Site
      tags:
      - Sites
    get:
      description: Get a Site in the organization.
      operationId: getSite
      security:
      - oauthFlow:
        - deployments.sites:read
      summary: Get Site
      tags:
      - Sites
    put:
      description: Update a Site in the organization.
      operationId: updateSite
      security:
      - oauthFlow:
        - deployments.sites:write
      summary: Update Site
      tags:
      - Sites
  /investigate/v2/bgp_routes/asn/{asn}/prefixes_for_asn.json:
    get:
      description: 'A response to a valid ASN returns an array of hash references.

        Each hash reference contains two keys: `geo` and `cidr`.

        Geo is a hash reference with the country name and country code

        (the code corresponds to the country code list for ISO-3166-1 alpha-2).

        CIDR contains the IP prefix for this ASN.

        '
      operationId: getBgpRoutesAsn
      security:
      - oauthFlow:
        - investigate.investigate:read
      summary: Get BGP Route Information for ASN
      tags:
      - AS Information for a Domain
  /investigate/v2/bgp_routes/ip/{ip}/as_for_ip.json:
    get:
      description: 'This endpoint provides data about ASN and IP relationships,

        showing how IP addresses are related to each other and to the regional registries.

        You can find out more about the IP space associated with an AS

        and correlate BGP routing information between AS.


        When querying an IP to find which AS (Autonomous System), it is helpful

        to find associated IP addresses. The AS is part of the BGP routing for that
        IP.


        A valid result returns an array of hash references.

        The hash reference contains information about the AS such as the ASN,

        the CIDR prefix of the AS, the Internet Registry (RIR) number (0 through 6),

        the Description of the AS and the creation date for the AS.

        An empty response returns an empty array ([]).'
      operationId: getBgpRoutesIp
      security:
      - oauthFlow:
        - investigate.investigate:read
      summary: Get BGP Route Information for IP
      tags:
      - AS Information for a Domain
  /investigate/v2/domains/categorization:
    post:
      description: 'Provide a list of domains and look up the status, and security
        and content category IDs for each domain.

        The domain status is a numerical value determined by the Cisco Security Labs
        team.

        Valid status values are: ''-1'' (malicious), ''1'' (safe), or ''0'' (undetermined
        status).

        '
      operationId: postDomainsCategorization
      security:
      - oauthFlow:
        - investigate.bulk:read
      summary: Check Status and Categorization of Domains
      tags:
      - Domain Status and Categorization
  /investigate/v2/domains/categorization/{domain}:
    get:
      description: 'Look up the status, and security and content category IDs for
        the domain.

        The domain status is a numerical value determined by the Cisco Security Labs
        team.

        Valid status values are: ''-1'' (malicious), ''1'' (safe), or ''0'' (undetermined
        status).

        '
      operationId: getDomainsCategorization
      security:
      - oauthFlow:
        - investigate.investigate:read
      summary: Get Domain Status and Categorization
      tags:
      - Domain Status and Categorization
  /investigate/v2/domains/risk-score/{domain}:
    get:
      description: 'The Investigate Risk Score is based on an analysis of

        the lexical characteristics of the domain name

        and patterns in queries and requests to the domain.

        The risk score is scaled from 0 to 100 where 100 is the highest risk

        and 0 represents no risk at all. Periodically, Investigate updates this score
        based

        on additional inputs.

        A domain blocked by Secure Access receives a score of 100.'
      operationId: getDomainsRiskScore
      security:
      - oauthFlow:
        - investigate.investigate:read
      summary: Get Risk Score for Domain
      tags:
      - Security Information for a Domain
  /investigate/v2/domains/volume/{domain}:
    get:
      description: 'List the query volume for a domain over the last 30 days.

        If there is no information about the domain, Investigate returns an empty
        array.

        As the query takes time to generate, the last two hours may be blank.

        '
      operationId: getDomainVolume
      security:
      - oauthFlow:
        - investigate.investigate:read
      summary: Get Domain Volume
      tags:
      - Domain Volume
  /investigate/v2/links/name/{domain}:
    get:
      description: 'List the domain names that are frequently requested around

        the same time (up to 60 seconds before or after) as the given domain name,

        but that are not frequently associated with other domain names.'
      operationId: getLinksName
      security:
      - oauthFlow:
        - investigate.investigate:read
      summary: Get Related Domains for Domain
      tags:
      - Related Domains for a Domain
  /investigate/v2/pdns/domain/{domain}:
    get:
      description: Get the Resource Record (RR) data for DNS responses, and categorization
        data, where the answer (or rdata) is the domain(s).
      operationId: getPassiveDNSDomain
      security:
      - oauthFlow:
        - investigate.investigate:read
      summary: Get Resource Records for Domain
      tags:
      - Passive DNS
  /investigate/v2/pdns/ip/{ip}:
    get:
      description: Get the Resource Record (RR) data for DNS responses, and categorization
        data, where the answer (or rdata) is the domain(s).
      operationId: getPassiveDNSIp
      security:
      - oauthFlow:
        - investigate.investigate:read
      summary: Get Resource Records for IP
      tags:
      - Passive DNS
  /investigate/v2/pdns/name/{domain}:
    get:
      description: The Passive DNS endpoint provides historical data from the Secure
        Access resolvers for domains, IPs, and other resource records.
      operationId: getPassiveDNSName
      security:
      - oauthFlow:
        - investigate.investigate:read
      summary: Get Resource Records for Name
      tags:
      - Passive DNS
  /investigate/v2/pdns/raw/{anystring}:
    get:
      description: Get the Resource Record (RR) data for DNS responses, and categorization
        data, where the answer (or rdata) could be anything.
      operationId: getPassiveDNSRaw
      security:
      - oauthFlow:
        - investigate.investigate:read
      summary: Get Resource Records for Raw Data
      tags:
      - Passive DNS
  /investigate/v2/recommendations/name/{domain}.json:
    get:
      description: 'List the co-occurences for the specified domain.

        A co-occurrence is when two or more domains are accessed by the same users
        within a small window of time.

        Co-occurring domains are not necessarily problematic; legitimate sites co-occur
        with each other as a part

        of normal web activity. However, unusual or suspicious co-occurences can provide
        additional information regarding attacks.

        To determine co-occurrences for a domain, a small time window of traffic across
        all of our datacenters is taken.

        Investigate checks the sites that end users visited before and after the domain
        was requested in the API call.'
      operationId: getRecommendationsName
      security:
      - oauthFlow:
        - investigate.investigate:read
      summary: Get Recommendations by Name
      tags:
      - Co-occurrences for a Domain
  /investigate/v2/sample/{hash}:
    get:
      description: 'Gather the information from the /samples endpoint, then pivot
        using the checksums

        of the samples revealed in your initial query.

        This pivot can reveal large chunks of new data about the malware being researched.

        Returns a variety of data as nested JSON arrays.

        The initial results array contains the information about the original sample.

        These results are described first and are, in effect, the samples of the sample.

        '
      operationId: getSampleHash
      security:
      - oauthFlow:
        - investigate.investigate:read
      summary: Get Samples for Hash
      tags:
      - Cisco Secure Malware Analytics Integration
  /investigate/v2/sample/{hash}/artifacts:
    get:
      description: 'Other samples associated with this sample. The sample data does
        not include a threat score.

        Artifacts are only available for Cisco Secure Malware Analytics customers.'
      operationId: getSampleHashArtifacts
      security:
      - oauthFlow:
        - investigate.investigate:read
      summary: Get Samples for Hash Artifacts
      tags:
      - Cisco Secure Malware Analytics Integration
  /investigate/v2/sample/{hash}/behaviors:
    get:
      description: 'Get the information about specific actions or unique properties
        of this sample,

        especially local to your network or the computer where the sample is run.'
      operationId: getSampleHashBehaviors
      security:
      - oauthFlow:
        - investigate.investigate:read
      summary: Get Samples for Hash Behaviors
      tags:
      - Cisco Secure Malware Analytics Integration
  /investigate/v2/sample/{hash}/connections:
    get:
      description: Information about network activity associated with this sample,
        such as connections to other domains or IPs.
      operationId: getSampleHashConnections
      security:
      - oauthFlow:
        - investigate.investigate:read
      summary: Get Samples for Hash Connections
      tags:
      - Cisco Secure Malware Analytics Integration
  /investigate/v2/samples/{destination}:
    get:
      description: 'Specify a domain, IP, or URL. Use the destination to search for
        all samples

        associated with the destination. The default number of items in a response
        is 10. You can extend the limit.

        You must have a license for Cisco Secure Malware Analytics to receive the
        samples data.


        Cisco Secure Malware Analytics retains checksum samples for one year.

        You may find that Investigate previously listed a sample related

        to a destination. If Cisco Secure Malware Analytics no longer contains a sample

        related to the destination, Investigate does not display the sample in the
        list

        of associated samples.


        An error may occur when the requested destination is not in a valid format,

        if the requested host is not found in our database, or if there is no data
        available

        for the destination that you have requested. CIDR subnets (for example: 10.10.10.0/24)
        and pattern search is not supported.

        '
      operationId: getSamplesDestination
      security:
      - oauthFlow:
        - investigate.investigate:read
      summary: Get Samples for Domain, IP, or URL
      tags:
      - Cisco Secure Malware Analytics Integration
  /investigate/v2/search/{expression}:
    get:
      description: List the newly seen domains that match a regular expression pattern.
      operationId: getSearch
      security:
      - oauthFlow:
        - investigate.investigate:read
      summary: Get Domains by Search
      tags:
      - Search Domain
  /investigate/v2/security/name/{domain}:
    get:
      description: 'List multiple scores or security features for a domain. You can
        use the scores

        or security features to determine relevant data points and build insights
        on the reputation

        or security risk posed by the site. No one security information feature is
        conclusive.

        Instead, consider these features as part of your security research.'
      operationId: getSecurityName
      security:
      - oauthFlow:
        - investigate.investigate:read
      summary: Get Security Score Information for Domain
      tags:
      - Security Information for a Domain
  /investigate/v2/subdomains/{domain}:
    get:
      description: 'Get the subdomains of a given domain. If there is no subdomain
        for the domain, Investigate returns an empty array.

        '
      operationId: getSubDomains
      security:
      - oauthFlow:
        - investigate.investigate:read
      summary: Get Subdomains for Domain
      tags:
      - Subdomains for a Domain
  /investigate/v2/timeline/{name}:
    get:
      description: 'List the historical tagging timeline for a given IP, domain, or
        URL.

        Investigate sorts the timeline items in descending order using the timestamp
        field.

        Each timeline item includes lists of security category,

        attack, or threat type associated with the destination.

        Use the Tagging Timeline endpoint to verify when Secure Access assigned or
        removed

        a security category, attack, or threat type.

        If the current timeline item contains the security category, type of attack,

        or threat type not found in the previous timeline item,

        Secure Access updated the current timeline item.

        If the current timeline item does not contain the security category, attack,

        or threat type found in the previous timeline item,

        Secure Access removed the security category, type of attack,

        or threat type.

        '
      operationId: getTimeline
      security:
      - oauthFlow:
        - investigate.investigate:read
      summary: Get Tagging Timeline for Destination
      tags:
      - Tagging Timeline
  /investigate/v2/topmillion:
    get:
      description: 'List the most seen domains in Secure Access. You can download
        the data in a zip file,

        or use the Investigate API to stream the data into a SIEM.

        The popularity list contains our most queried domains based on passive DNS
        usage across

        the Secure Access global network of more than 180 billion requests per day
        with many tens of millions

        of unique active users, in more than 165 countries.

        The metric does not only consist of browser-based http requests from users
        but also takes

        in to account the number of unique client IPs invoking this domain relative
        to the sum of all requests

        to all domains.

        Our popularity ranking reflects the domain''s relative internet activity agnostic

        to the invocation protocols and applications where as site ranking models
        (such as Alexa) focus

        on the web activity over port 80 (primarily from browsers).

        In addition, the Secure Access popularity algorithm also applies data normalization
        techniques

        to smooth potential biases that may occur due to sampling of DNS usage data.

        '
      operationId: getTopmillion
      security:
      - oauthFlow:
        - investigate.investigate:read
      summary: Get Top Most Seen Domains
      tags:
      - Popularity List-Top Million Domains
  /investigate/v2/whois/{domain}:
    get:
      description: 'Get the WHOIS information for the specified email addresses,

        nameservers, and domains. You can search by multiple email addresses or multiple
        nameservers.

        This documentation outlines the following API endpoints:

        email (single and multiple), domain record (current and historical), and nameserver
        (single and multiple).

        In some instances, WHOIS information can be irregular as there are no standards

        between domain registrars and large volumes of information can be returned
        from a query.

        As such, both the email and nameserver WHOIS endpoints have a limit of 500
        results,

        which you can reduce to a smaller set of results.

        There is an `offset` parameter that can be leveraged to retrieve the entire
        set

        of domain entries for a given email without any limitation. Only the email
        parameter

        supports this.

        You can sort the email parameter by filtering the entries based on the timestamp
        field.

        If a domain, email, or nameserver has no known WHOIS information, Investigate
        returns `HTTP 404`.

        If a domain, email or nameserver does not exist, Investigate returns `HTTP
        404`.

        '
      operationId: getWhois
      security:
      - oauthFlow:
        - investigate.investigate:read
      summary: Get WHOIS Information for Domain
      tags:
      - WHOIS Information for a Domain
  /investigate/v2/whois/{domain}/history:
    get:
      description: 'Get a standard WHOIS response record for a single domain with
        available historical

        WHOIS data returned in an object. The information displayed varies by registrant.

        The default limit for history is 10. You can set another value with the `limit`
        query parameter.

        '
      operationId: getWhoisHistory
      security:
      - oauthFlow:
        - investigate.investigate:read
      summary: Get WHOIS History for Domain
      tags:
      - WHOIS Information for a Domain
  /investigate/v2/whois/emails/{email}:
    get:
      description: 'Get the email address or addresses of the registrar for the domain
        or domains. The results include

        the total number of results for domains registered by this email address and
        a list

        of the first 500 domains associated with this email.

        You can pivot on the email address to find other malicious domains registered
        by the same email.

        This endpoint is limited to a maximum of 500 results, which are the first
        500 gathered from the database.

        Reduce the number of results by setting the `limit` query parameter.

        **Note:** Due to the sample length, Investigate may truncate a sample.'
      operationId: getWhoisEmail
      security:
      - oauthFlow:
        - investigate.investigate:read
      summary: Get WHOIS Email Information
      tags:
      - WHOIS Information for a Domain
  /investigate/v2/whois/nameservers:
    get:
      description: 'Get WHOIS information for the nameservers. To search by multiple
        nameservers, provide

        a comma-delimited list of domain names for the `nameServerList` query parameter.

        For example: `ns1.google.com,ns2.google.com`.'
      operationId: getWhoisNameservers
      security:
      - oauthFlow:
        - investigate.investigate:read
      summary: Get WHOIS Information for Nameservers
      tags:
      - WHOIS Information for a Domain
  /investigate/v2/whois/nameservers/{nameserver}:
    get:
      description: 'Get WHOIS information for the nameserver.

        As a nameserver can potentially register hundreds or thousands of domains,

        the server limits the number of results to 500.'
      operationId: getWhoisNameserver
      security:
      - oauthFlow:
        - investigate.investigate:read
      summary: Get WHOIS Information for Nameserver
      tags:
      - WHOIS Information for a Domain
  /investigate/v2/whois/search/{searchField}/{regexExpression}:
    get:
      description: 'Performs a regular expression (RegEx) search on the WHOIS data
        (domain, nameserver, and email fields)

        that was updated or created in the specified time range.

        Returns a list of ten WHOIS records that match the specified RegEx expression.

        Use the `offset` query parameter to paginate the collection.

        By default, Investigate sorts by the `updated` field.

        '
      operationId: getWhoisSearch
      security:
      - oauthFlow:
        - investigate.investigate:read
      summary: Get WHOIS Information Search
      tags:
      - WHOIS Information for a Domain
  /policies/v2/applicationCategories:
    get:
      description: Get the Application Categories for the organization.
      operationId: getApplicationCategories
      security:
      - oauthFlow:
        - policies.applicationCategories:read
      summary: List Application Categories
      tags:
      - Application Categories
  /policies/v2/applicationLists:
    get:
      description: Get the application lists and the number of application lists in
        the organization.
      operationId: getApplicationLists
      security:
      - oauthFlow:
        - policies.applicationlists:read
      summary: Get Application Lists
      tags:
      - Application Lists
    post:
      description: Create an application list for the organization.
      operationId: createApplicationList
      security:
      - oauthFlow:
        - policies.applicationlists:write
      summary: Create Application List
      tags:
      - Application Lists
  /policies/v2/applicationLists/{applicationListId}:
    delete:
      description: Delete the application list in the organization.
      operationId: deleteApplicationList
      security:
      - oauthFlow:
        - policies.applicationlists:write
      summary: Delete Application List
      tags:
      - Application Lists
    get:
      description: Get the properties of the application list.
      operationId: getApplicationList
      security:
      - oauthFlow:
        - policies.applicationlists:read
      summary: Get Application List
      tags:
      - Application Lists
    put:
      description: Update the properties of the application list.
      operationId: putApplicationList
      security:
      - oauthFlow:
        - policies.applicationlists:write
      summary: Update Application List
      tags:
      - Application Lists
  /policies/v2/applications/usage:
    get:
      description: Get the list of application usage information for the application
        lists.
      operationId: updateUsageApplications
      security:
      - oauthFlow:
        - policies.applicationlists:read
      summary: Get Usage of Applications
      tags:
      - Application Lists
  /policies/v2/categorySettings:
    get:
      description: Get all Content Category settings in the organization.
      operationId: getCategorySettings
      security:
      - oauthFlow:
        - policies.contentCategories:read
      summary: List Content Categories
      tags:
      - Content Categories
  /policies/v2/destinationlists:
    get:
      description: Get the destination lists in your organization.
      operationId: getDestinationLists
      security:
      - oauthFlow:
        - policies.destinationLists:read
      summary: Get Destination Lists
      tags:
      - Destination Lists
    post:
      description: Create a destination list in your organization.
      operationId: createDestinationList
      security:
      - oauthFlow:
        - policies.destinationLists:write
      summary: Create Destination List
      tags:
      - Destination Lists
  /policies/v2/destinationlists/{destinationListId}:
    delete:
      description: Delete a destination list from your organization.
      operationId: deleteDestinationList
      security:
      - oauthFlow:
        - policies.destinationLists:write
      summary: Delete Destination List
      tags:
      - Destination Lists
    get:
      description: Get a destination list.
      operationId: getDestinationList
      security:
      - oauthFlow:
        - policies.destinationLists:read
      summary: Get Destination List
      tags:
      - Destination Lists
    patch:
      description: Update a destination list in your organization.
      operationId: updateDestinationLists
      security:
      - oauthFlow:
        - policies.destinationLists:write
      summary: Update Destination List
      tags:
      - Destination Lists
  /policies/v2/destinationlists/{destinationListId}/destinations:
    get:
      description: Get destinations in a destination list.
      operationId: getDestinations
      security:
      - oauthFlow:
        - policies.destinations:read
      summary: Get Destinations in Destination List
      tags:
      - Destinations
    post:
      description: Add destinations to a destination list.
      operationId: createDestinations
      security:
      - oauthFlow:
        - policies.destinations:write
      summary: Add Destinations to Destination List
      tags:
      - Destinations
  /policies/v2/destinationlists/{destinationListId}/destinations/remove:
    delete:
      description: 'Remove destinations from the destination list.


        **Note:** Accepts a list that contains no more than 500 destination IDs.


        You can retrieve a list of the destinations in the destination list through
        the GET `/destinationlists/{destinationListId}/destinations` operation.

        Then, to remove destinations in a destination list, provide a list of destination
        IDs in the request body of the

        DELETE `/destinationlists/{destinationListId}/destinations/remove` operation.'
      operationId: deleteDestinations
      security:
      - oauthFlow:
        - policies.destinations:write
      summary: Delete Destinations from Destination List
      tags:
      - Destinations
  /policies/v2/feeds:
    get:
      description: List the threat feeds for the third-party and custom security vendors
        integrated in Secure Access.
      operationId: getFeeds
      security:
      - oauthFlow:
        - policies.feeds:read
      summary: List Threat Feeds
      tags:
      - Feeds
    post:
      description: Create a threat feed for a third-party or custom security vendor.
      operationId: createFeed
      security:
      - oauthFlow:
        - policies.feeds:write
      summary: Create Threat Feed
      tags:
      - Feeds
  /policies/v2/feeds/{feedId}:
    delete:
      description: 'Delete the threat feed for a custom security vendor.

        **Note:** You cannot remove a threat feed for a third-party security vendor.
        You can only enable or disable a threat feed for a third-party security vendor.'
      operationId: deleteFeed
      security:
      - oauthFlow:
        - policies.feeds:write
      summary: Delete Threat Feed
      tags:
      - Feeds
    get:
      description: Get the properties of the threat feed for a third-party or custom
        security vendor.
      operationId: getFeed
      security:
      - oauthFlow:
        - policies.feeds:read
      summary: Get Threat Feed
      tags:
      - Feeds
    put:
      description: Update the properties of the threat feed for a third-party or custom
        security vendor.
      operationId: updateFeed
      security:
      - oauthFlow:
        - policies.feeds:write
      summary: Update Threat Feed
      tags:
      - Feeds
  /policies/v2/geolocations:
    get:
      description: 'List the regional information for the continents and countries.

        You can use the country code to create a block on the traffic defined in an
        internet access rule.'
      operationId: getRegionalLocations
      security:
      - oauthFlow:
        - policies.rules:read
      summary: List GeoLocations
      tags:
      - Access Rules
  /policies/v2/ipsSignatureProfiles:
    get:
      description: 'Get the list of custom and system-defined IPS profiles for the
        organization.

        The system-defined IPS profiles are:


        * Connectivity Over Security

        * Balanced Security and Connectivity

        * Security Over Connectivity

        * Maximum Detection'
      operationId: getIpsProfiles
      security:
      - oauthFlow:
        - policies.ipsconfig:read
      summary: List IPS Profiles
      tags:
      - IPS Profiles
    post:
      description: Create a custom IPS profile in the organization.
      operationId: createCustomIpsProfile
      security:
      - oauthFlow:
        - policies.ipsconfig:write
      summary: Create Custom IPS Profile
      tags:
      - IPS Profiles
  /policies/v2/ipsSignatureProfiles/{id}:
    delete:
      description: Delete the custom IPS profile in the organization.
      operationId: deleteCustomIpsProfile
      security:
      - oauthFlow:
        - policies.ipsconfig:write
      summary: Delete Custom IPS Profile
      tags:
      - IPS Profiles
    get:
      description: Get the IPS profile in the organization.
      operationId: getIpsProfile
      security:
      - oauthFlow:
        - policies.ipsconfig:read
      summary: Get IPS Profile
      tags:
      - IPS Profiles
    patch:
      description: Update the IPS profile in the organization.
      operationId: updateIpsProfile
      security:
      - oauthFlow:
        - policies.ipsconfig:write
      summary: Update IPS Profile
      tags:
      - IPS Profiles
  /policies/v2/ipsSignatureProfiles/{id}/signatures:
    get:
      description: Get the IPS signatures associated with the IPS profile.
      operationId: getSignaturesInSignatureProfile
      security:
      - oauthFlow:
        - policies.ipsconfig:read
      summary: Get Signatures in IPS Profile
      tags:
      - IPS Profiles
  /policies/v2/objects/networkObjectGroups:
    get:
      description: Get the Network Object Groups for the organization.
      operationId: getNetworkObjectGroups
      security:
      - oauthFlow:
        - policies.objects.networkObjectGroups:read
      summary: List Network Object Groups
      tags:
      - Network Object Groups
    post:
      description: Create a Network Object Group in the organization.
      operationId: createNetworkObjectGroup
      security:
      - oauthFlow:
        - policies.objects.networkObjectGroups:write
      summary: Create Network Object Group
      tags:
      - Network Object Groups
  /policies/v2/objects/networkObjectGroups/{networkObjectGroupId}:
    delete:
      description: Delete a Network Object Group in the organization.
      operationId: deleteNetworkObjectGroup
      security:
      - oauthFlow:
        - policies.objects.networkObjectGroups:write
      summary: Delete Network Object Group
      tags:
      - Network Object Groups
    get:
      description: Get a Network Object Group in the organization.
      operationId: getNetworkObjectGroup
      security:
      - oauthFlow:
        - policies.objects.networkObjectGroups:read
      summary: Get Network Object Group
      tags:
      - Network Object Groups
    put:
      description: Update a Network Object Group in the organization.
      operationId: updateNetworkObjectGroup
      security:
      - oauthFlow:
        - policies.objects.networkObjectGroups:write
      summary: Update Network Object Group
      tags:
      - Network Object Groups
  /policies/v2/objects/networkObjectGroups/{networkObjectGroupId}/references:
    get:
      description: 'Get the references for the Network Object Group in the organization.

        A reference is an access rule or other Network Object Group that includes
        a Network Object Group.'
      operationId: getReferencesForNetworkObjectGroup
      security:
      - oauthFlow:
        - policies.objects.networkObjectGroups:read
      summary: Get References for Network Object Group
      tags:
      - Network Object Groups
  /policies/v2/objects/networkObjectGroups/references:
    get:
      description: 'Get the references for the Network Object Groups in the organization.

        A reference is an access rule or other Network Object Group that includes
        a Network Object Group.'
      operationId: getReferencesForNetworkObjectGroups
      security:
      - oauthFlow:
        - policies.objects.networkObjectGroups:read
      summary: List References for Network Object Groups
      tags:
      - Network Object Groups
  /policies/v2/objects/networkObjects:
    get:
      description: Get the Network Objects in the organization.
      operationId: listNetworkObjects
      security:
      - oauthFlow:
        - policies.objects.networkObjects:read
      summary: List Network Objects
      tags:
      - Network Objects
    post:
      description: Create a Network Object in the organization.
      operationId: createNetworkObject
      security:
      - oauthFlow:
        - policies.objects.networkObjects:write
      summary: Create Network Object
      tags:
      - Network Objects
  /policies/v2/objects/networkObjects/{networkObjectId}:
    delete:
      description: Delete a Network Object in the organization.
      operationId: deleteNetworkObject
      security:
      - oauthFlow:
        - policies.objects.networkObjects:write
      summary: Delete Network Object
      tags:
      - Network Objects
    get:
      description: Get a Network Object in the organization.
      operationId: getNetworkObject
      security:
      - oauthFlow:
        - policies.objects.networkObjects:read
      summary: Get Network Object
      tags:
      - Network Objects
    put:
      description: Update a Network Object in the organization.
      operationId: updateNetworkObject
      security:
      - oauthFlow:
        - policies.objects.networkObjects:write
      summary: Update Network Object
      tags:
      - Network Objects
  /policies/v2/objects/networkObjects/{networkObjectId}/references:
    get:
      description: 'Get the references for the Network Object in the organization.

        A reference is an access rule or Network Object Group that includes a Network
        Object.'
      operationId: getReferencesForNetworkObject
      security:
      - oauthFlow:
        - policies.objects.networkObjects:read
      summary: Get References for Network Object
      tags:
      - Network Objects
  /policies/v2/objects/networkObjects/references:
    get:
      description: 'Get the references for the Network Objects in the organization.

        A reference is an access rule or Network Object Group that includes a Network
        Object.'
      operationId: getReferencesForNetworkObjects
      security:
      - oauthFlow:
        - policies.objects.networkObjects:read
      summary: List References for Network Objects
      tags:
      - Network Objects
  /policies/v2/objects/networkObjects/upload:
    post:
      description: Upload a CSV file with the properties that are required for creating
        the Network Objects.
      operationId: createUploadNetworkObjects
      security:
      - oauthFlow:
        - policies.objects.networkObjects:write
      summary: Upload Network Objects
      tags:
      - Network Objects
  /policies/v2/objects/networkObjects/validate:
    post:
      description: Validate a CSV file that includes the properties for creating the
        Network Objects. The system validates the properties for each Network Object
        in the file and returns a list of the validation errors.
      operationId: createValidateNetworkObjects
      security:
      - oauthFlow:
        - policies.objects.networkObjects:write
      summary: Validate Network Objects
      tags:
      - Network Objects
  /policies/v2/objects/serviceObjectGroups:
    get:
      description: Get the Service Object Groups in the organization.
      operationId: getServiceObjectGroups
      security:
      - oauthFlow:
        - policies.objects.serviceObjectGroups:read
      summary: List Service Object Groups
      tags:
      - Service Object Groups
    post:
      description: Create a Service Object Group in the organization.
      operationId: createServiceObjectGroup
      security:
      - oauthFlow:
        - policies.objects.serviceObjectGroups:write
      summary: Create Service Object Group
      tags:
      - Service Object Groups
  /policies/v2/objects/serviceObjectGroups/{serviceObjectGroupId}:
    delete:
      description: Delete a Service Object Group in the organization.
      operationId: deleteServiceObjectGroup
      security:
      - oauthFlow:
        - policies.objects.serviceObjectGroups:write
      summary: Delete Service Object Group
      tags:
      - Service Object Groups
    get:
      description: Get a Service Object Group in the organization.
      operationId: getServiceObjectGroup
      security:
      - oauthFlow:
        - policies.objects.serviceObjectGroups:read
      summary: Get Service Object Group
      tags:
      - Service Object Groups
    put:
      description: Update a Service Object Group in the organization.
      operationId: updateServiceObjectGroup
      security:
      - oauthFlow:
        - policies.objects.serviceObjectGroups:write
      summary: Update Service Object Group
      tags:
      - Service Object Groups
  /policies/v2/objects/serviceObjectGroups/{serviceObjectGroupId}/references:
    get:
      description: 'Get the references for a Service Object Group in the organization.

        A reference is an access rule or other Service Object Group that includes
        a Service Object Group.'
      operationId: getReferencesForServiceObjectGroup
      security:
      - oauthFlow:
        - policies.objects.serviceObjectGroups:read
      summary: Get References for Service Object Group
      tags:
      - Service Object Groups
  /policies/v2/objects/serviceObjectGroups/references:
    get:
      description: 'Get all references for the Service Object Groups in the organization.

        A reference is an access rule or other Service Object Group that includes
        a Service Object Group.'
      operationId: getReferencesForServiceObjectGroups
      security:
      - oauthFlow:
        - policies.objects.serviceObjectGroups:read
      summary: List References for Service Object Groups
      tags:
      - Service Object Groups
  /policies/v2/objects/serviceObjects:
    get:
      description: Get the Service Objects in the organization.
      operationId: getServiceObjects
      security:
      - oauthFlow:
        - policies.objects.serviceObjects:read
      summary: List Service Objects
      tags:
      - Service Objects
    post:
      description: Create a Service Object for the organization.
      operationId: createServiceObject
      security:
      - oauthFlow:
        - policies.objects.serviceObjects:write
      summary: Create Service Object
      tags:
      - Service Objects
  /policies/v2/objects/serviceObjects/{serviceObjectId}:
    delete:
      description: Delete a Service Object in the organization.
      operationId: deleteServiceObject
      security:
      - oauthFlow:
        - policies.objects.serviceObjects:write
      summary: Delete Service Object
      tags:
      - Service Objects
    get:
      description: Get a Service Object in the organization.
      operationId: getServiceObject
      security:
      - oauthFlow:
        - policies.objects.serviceObjects:read
      summary: Get Service Object
      tags:
      - Service Objects
    put:
      description: Update a Service Object in the organization.
      operationId: updateServiceObject
      security:
      - oauthFlow:
        - policies.objects.serviceObjects:write
      summary: Update Service Object
      tags:
      - Service Objects
  /policies/v2/objects/serviceObjects/{serviceObjectId}/references:
    get:
      description: 'Get the references for a Service Object in the organization.

        A reference is an access rule or Service Object Group that includes a Service
        Object.'
      operationId: getReferencesForServiceObject
      security:
      - oauthFlow:
        - policies.objects.serviceObjects:read
      summary: Get References for Service Object
      tags:
      - Service Objects
  /policies/v2/objects/serviceObjects/references:
    get:
      description: 'Get the references for the Service Objects in the organization.

        A reference is an access rule or Service Object Group that includes a Service
        Object.'
      operationId: getReferencesForServiceObjects
      security:
      - oauthFlow:
        - policies.objects.serviceObjects:read
      summary: List References for Service Objects
      tags:
      - Service Objects
  /policies/v2/objects/serviceObjects/upload:
    post:
      description: Upload a CSV file with the properties that are required for creating
        the Service Objects.
      operationId: createUploadServiceObjects
      security:
      - oauthFlow:
        - policies.objects.serviceObjects:write
      summary: Upload Service Objects
      tags:
      - Service Objects
  /policies/v2/objects/serviceObjects/validate:
    post:
      description: Validate a CSV file that includes the properties for creating the
        Service Objects. The system validates the properties for each Service Object
        in the file and returns a list of the validation errors.
      operationId: createValidateServiceObjects
      security:
      - oauthFlow:
        - policies.objects.serviceObjects:write
      summary: Validate Service Objects
      tags:
      - Service Objects
  /policies/v2/objects/unifiedNetworkObjects:
    get:
      description: Get the Network Objects and Network Object Groups in the organization.
      operationId: listUnifiedNetworkObjects
      security:
      - oauthFlow:
        - policies.objects.networkObjects:read
      summary: List Network Objects and Network Groups
      tags:
      - Unified Objects
  /policies/v2/objects/unifiedServiceObjects:
    get:
      description: Get the Service Objects and Service Object Groups in the organization.
      operationId: listUnifiedServiceObjects
      security:
      - oauthFlow:
        - policies.objects.serviceObjects:read
      summary: List Service Objects and Service Groups
      tags:
      - Unified Objects
  /policies/v2/privateResourceGroups:
    get:
      description: List the Private Resource Groups for the organization.
      operationId: listResourceGroups
      security:
      - oauthFlow:
        - policies.privateresourcegroups:read
      summary: List Resource Groups
      tags:
      - Resource Groups
    post:
      description: 'Create a Private Resource Group for the organization.

        You can create a maximum of 1000 Private Resource Groups.'
      operationId: addPrivateResourceGroup
      security:
      - oauthFlow:
        - policies.privateresourcegroups:write
      summary: Create Resource Group
      tags:
      - Resource Groups
  /policies/v2/privateResourceGroups/{id}:
    delete:
      description: 'Delete the Private Resource Group from the organization.

        Before deleting the Private Resource Group, Secure Access removes the Private
        Resources

        from the Private Resource Group.'
      operationId: deletePrivateResourceGroup
      security:
      - oauthFlow:
        - policies.privateresourcegroups:write
      summary: Delete Resource Group
      tags:
      - Resource Groups
    get:
      description: Get the details about a Private Resource Group.
      operationId: getPrivateResourceGroup
      security:
      - oauthFlow:
        - policies.privateresourcegroups:read
      summary: Get Resource Group
      tags:
      - Resource Groups
    put:
      description: Update the `name` and `description` properties on the Private Resource
        Group.
      operationId: putPrivateResourceGroup
      security:
      - oauthFlow:
        - policies.privateresourcegroups:write
      summary: Update Resource Group
      tags:
      - Resource Groups
  /policies/v2/privateResources:
    get:
      description: List the Private Resources for the organization.
      operationId: listPrivateResources
      security:
      - oauthFlow:
        - policies.privateresources:read
      summary: List Private Resources
      tags:
      - Private Resources
    post:
      description: 'Create a Private Resource for the organization. You can add at
        most 1000 Private Resources to an organization.

        When you add a Private Resource enabled for Zero Trust Access, the Zero Trust
        Access service automatically manages the private applications.'
      operationId: addPrivateResource
      security:
      - oauthFlow:
        - policies.privateresources:write
      summary: Create Private Resource
      tags:
      - Private Resources
  /policies/v2/privateResources/{id}:
    delete:
      description: 'Delete a Private Resource. Remove the Private Resource from any
        Private Resource Groups before deleting the resource.

        If the Private Resource is the only resource in your organization''s Private
        Resource Groups,

        then Secure Access also removes the Private Resource Groups.'
      operationId: deletePrivateResource
      security:
      - oauthFlow:
        - policies.privateresources:write
      summary: Delete Private Resource
      tags:
      - Private Resources
    get:
      description: Get the details about a Private Resource.
      operationId: getPrivateResource
      security:
      - oauthFlow:
        - policies.privateresources:read
      summary: Get Private Resource
      tags:
      - Private Resources
    put:
      description: 'Update the properties on a Private Resource.

        You can set the following Private Resource properties: `name`, `description`,
        `resourceAddresses`, `dnsServerId`, `certificateId`,

        `protocol`, `sni`, and `sslVerificationEnabled`.'
      operationId: putPrivateResource
      security:
      - oauthFlow:
        - policies.privateresources:write
      summary: Update Private Resource
      tags:
      - Private Resources
  /policies/v2/rules:
    get:
      description: List the rules in the policy for the organization.
      operationId: listRules
      security:
      - oauthFlow:
        - policies.rules:read
      summary: List Rules
      tags:
      - Access Rules
    post:
      description: Create a rule on the policy for the organization.
      operationId: addRule
      security:
      - oauthFlow:
        - policies.rules:write
      summary: Create Rule
      tags:
      - Access Rules
    put:
      description: Enable or disable the rules on the policy.
      operationId: putRules
      security:
      - oauthFlow:
        - policies.rules:write
      summary: Enable Rules
      tags:
      - Access Rules
  /policies/v2/rules/{ruleId}:
    delete:
      description: Delete a rule on the policy for the organization.
      operationId: deleteRule
      security:
      - oauthFlow:
        - policies.rules:write
      summary: Delete Rule
      tags:
      - Access Rules
    get:
      description: Get the details about the rule.
      operationId: getRule
      security:
      - oauthFlow:
        - policies.rules:read
      summary: Get Rule
      tags:
      - Access Rules
    put:
      description: Update the properties on the rule.
      operationId: putRule
      security:
      - oauthFlow:
        - policies.rules:write
      summary: Update Rule
      tags:
      - Access Rules
  /policies/v2/securityProfiles:
    get:
      description: Get all Security profiles in the organization.
      operationId: getSecurityProfiles
      security:
      - oauthFlow:
        - policies.securityProfiles:read
      summary: List Security Profiles
      tags:
      - Security Profiles
  /policies/v2/securityProfiles/{profileId}:
    get:
      description: Get the properties of the Security Profile.
      operationId: getSecurityProfile
      security:
      - oauthFlow:
        - policies.securityProfiles:read
      summary: Get Security Profile
      tags:
      - Security Profiles
  /policies/v2/settingTypes:
    get:
      description: List the policy setting types.
      operationId: getPolicySettingTypes
      security:
      - oauthFlow:
        - policies.settings:read
      summary: List Policy Setting Types
      tags:
      - Rule Settings and Defaults
  /policies/v2/settingTypes/{settingName}:
    get:
      description: Get the type of the policy setting.
      operationId: getSettingTypesByName
      security:
      - oauthFlow:
        - policies.settings:read
      summary: Get Policy Setting Type
      tags:
      - Rule Settings and Defaults
  /policies/v2/settings:
    get:
      description: Get the global policy settings and rule defaults for the organization.
      operationId: getPolicySettings
      security:
      - oauthFlow:
        - policies.settings:read
      summary: Get Rule Defaults and Global Policy Settings
      tags:
      - Rule Settings and Defaults
    put:
      description: Update the rule defaults and global policy settings.
      operationId: putPolicySettings
      security:
      - oauthFlow:
        - policies.settings:write
      summary: Update Rule Defaults and Global Policy Settings
      tags:
      - Rule Settings and Defaults
  /policies/v2/settings/{settingName}:
    get:
      description: Get the policy setting identified by the setting name.
      operationId: getPolicySetting
      security:
      - oauthFlow:
        - policies.settings:read
      summary: Get Policy Setting
      tags:
      - Rule Settings and Defaults
    put:
      description: Update the policy setting.
      operationId: putPolicySetting
      security:
      - oauthFlow:
        - policies.settings:write
      summary: Update Policy Setting
      tags:
      - Rule Settings and Defaults
  /policies/v2/tenantControls/profiles:
    get:
      description: Get the Tenant Controls profiles for the organization.
      operationId: getTenantControlsProfiles
      security:
      - oauthFlow:
        - policies.tenantControlsProfiles:read
      summary: List Tenant Controls Profiles
      tags:
      - Tenant Controls Profiles
  /reports/v2/activity:
    get:
      description: 'List all activities (dns/proxy/firewall/ip/intrusion/ztna/decryption)
        within the timeframe.

        **Note:** The IP activity report is not available.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getActivities
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Activities (All)
      tags:
      - Activity
  /reports/v2/activity/amp-retrospective:
    get:
      description: 'List all AMP retrospective activity within the timeframe.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getActivityAmpRetrospective
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Activity AMP Retrospective
      tags:
      - Activity
  /reports/v2/activity/decryption:
    get:
      description: 'List all decryption entries within the timeframe.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getActivityDecryption
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Activity Decryption
      tags:
      - Activity
  /reports/v2/activity/dns:
    get:
      description: 'List all DNS entries within the timeframe.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getActivityDns
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Activity DNS
      tags:
      - Activity
  /reports/v2/activity/firewall:
    get:
      description: 'List all firewall activity within the timeframe.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getActivityFirewall
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Activity Firewall
      tags:
      - Activity
  /reports/v2/activity/intrusion:
    get:
      description: 'List all Intrusion Prevention System (IPS) activity within the
        timeframe.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getActivityIntrusion
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Activity Intrusion
      tags:
      - Activity
  /reports/v2/activity/ip:
    get:
      description: '(Deprecated) List all IP activity within the timeframe.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getActivityIP
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Activity IP
      tags:
      - Activity
  /reports/v2/activity/proxy:
    get:
      description: 'List all proxy entries within the timeframe.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getActivityProxy
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Activity Proxy
      tags:
      - Activity
  /reports/v2/activity/ztna:
    get:
      description: 'List all Zero Trust Network Access (ZTNA) entries within the timeframe.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getActivityZTNA
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Activity ZTNA
      tags:
      - Activity
  /reports/v2/apiUsage/keys:
    get:
      description: Get the API key usage information, including the total number of
        API requests within a specific time period.
      operationId: getAPIUsageKeys
      security:
      - oauthFlow:
        - reports.apiusage:read
      summary: Get Keys
      tags:
      - API Usage Report
  /reports/v2/apiUsage/requests:
    get:
      description: 'Get the information about the API requests for the organization
        within a specific time period, including

        the total number of API requests for the type of client program.'
      operationId: getAPIUsageRequests
      security:
      - oauthFlow:
        - reports.apiusage:read
      summary: Get Requests
      tags:
      - API Usage Report
  /reports/v2/apiUsage/responses:
    get:
      description: 'Get the information about the API responses for the organization
        within a specific time period, including

        the total number of API responses and the HTTP status codes.'
      operationId: getAPIUsageResponses
      security:
      - oauthFlow:
        - reports.apiusage:read
      summary: Get Responses
      tags:
      - API Usage Report
  /reports/v2/apiUsage/summary:
    get:
      description: Get the total number API requests, and the counts of the successful
        and failed API requests within a specific time period.
      operationId: getAPIUsageSummary
      security:
      - oauthFlow:
        - reports.apiusage:read
      summary: Get Summary
      tags:
      - API Usage Report
  /reports/v2/app-connectors/detailed-stats-timerange:
    get:
      description: 'Get detailed Resource Connector statistics for the connector IDs,
        includes average CPU utilization, total request,

        group ID, and timestamp for every connector ID.


        **Access Scope:** Reports > Private Resources > Read-Only'
      operationId: getDetailedStatsForAppConnector
      security:
      - oauthFlow:
        - reports.privateResources:read
      summary: Get Detailed Resource Connector Statistics
      tags:
      - Resource Connectors
  /reports/v2/app-connectors/groups/detailed-stats-timerange:
    get:
      description: 'Get detailed Resource Connector Group statistics for either group
        IDs (`groupIds`) or CPU Threshold (`cputhreshold`) parameters,

        The response includes the average CPU utilization and timestamp for every
        group in a series of time ranges.


        **Access Scope:** Reports > Private Resources > Read-Only'
      operationId: getDetailedStatsForAppConnectorGroups
      security:
      - oauthFlow:
        - reports.privateResources:read
      summary: Get Detailed Resource Connector Group Statistics
      tags:
      - Resource Connectors
  /reports/v2/app-connectors/groups/overloaded-count:
    get:
      description: 'Get the count of the overloaded groups that have a CPU Threshold
        greater than the CPU Threshold (`cputhreshold`) value.


        **Access Scope:** Reports > Private Resources > Read-Only'
      operationId: getOverloadedGroupsCount
      security:
      - oauthFlow:
        - reports.privateResources:read
      summary: Get Count of Overloaded Groups
      tags:
      - Resource Connectors
  /reports/v2/appDiscovery/applicationCategories:
    get:
      description: List all application categories.
      operationId: getApplicationCategoriesreportsappdiscoveryapplicationcategories
      security:
      - oauthFlow:
        - reports.appDiscovery:read
      summary: List Application Categories
      tags:
      - Application Categories
  /reports/v2/appDiscovery/applications:
    get:
      description: List all discovered applications.
      operationId: getApplicationsAppDiscovery
      security:
      - oauthFlow:
        - reports.appDiscovery:read
      summary: List Applications
      tags:
      - Applications
    patch:
      description: Update the labels for the applications.
      operationId: patchApplications
      security:
      - oauthFlow:
        - reports.appDiscovery:write
      summary: Update Applications
      tags:
      - Applications
  /reports/v2/appDiscovery/applications/{applicationId}:
    get:
      description: Get an application by ID.
      operationId: getApplication
      security:
      - oauthFlow:
        - reports.appDiscovery:read
      summary: Get Application
      tags:
      - Applications
    patch:
      description: Update the label for the application. Provide an application label
        in the request body.
      operationId: updateApplication
      security:
      - oauthFlow:
        - reports.appDiscovery:write
      summary: Update Application
      tags:
      - Applications
  /reports/v2/appDiscovery/applications/{applicationId}/attributes:
    get:
      description: List all attributes for the application.
      operationId: getApplicationAttributes
      security:
      - oauthFlow:
        - reports.appDiscovery:read
      summary: List Application Attributes
      tags:
      - Applications
  /reports/v2/appDiscovery/applications/{applicationId}/identities:
    get:
      description: List all identities for the application.
      operationId: getApplicationIdentities
      security:
      - oauthFlow:
        - reports.appDiscovery:read
      summary: List Application Identities
      tags:
      - Applications
  /reports/v2/appDiscovery/applications/{applicationId}/risk:
    get:
      description: Get the risk for the application.
      operationId: getApplicationRisk
      security:
      - oauthFlow:
        - reports.appDiscovery:read
      summary: Get Application Risk
      tags:
      - Applications
  /reports/v2/appDiscovery/applications/info:
    get:
      description: List the information about the applications.
      operationId: getApplicationsInfo
      summary: List Information for Applications
      tags:
      - Applications
  /reports/v2/appDiscovery/protocols:
    get:
      description: List all protocols.
      operationId: getProtocols
      security:
      - oauthFlow:
        - reports.appDiscovery:read
      summary: List Protocols
      tags:
      - Protocols
  /reports/v2/appDiscovery/protocols/{protocolId}:
    get:
      description: Get protocol by ID.
      operationId: getProtocol
      security:
      - oauthFlow:
        - reports.appDiscovery:read
      summary: Get Protocol
      tags:
      - Protocols
  /reports/v2/appDiscovery/protocols/{protocolId}/identities:
    get:
      description: List identities for a specific protocol.
      operationId: getProtocolIdentities
      security:
      - oauthFlow:
        - reports.appDiscovery:read
      summary: List Protocol Identities
      tags:
      - Identities
  /reports/v2/applications:
    get:
      description: 'List the applications.


        **Access Scope:** Reports > Utilities > Read-Only'
      operationId: getApplications
      security:
      - oauthFlow:
        - reports.utilities:read
      summary: Get Applications
      tags:
      - Utility
  /reports/v2/bandwidth-by-hour:
    get:
      description: 'List the bandwidth in bytes within the timeframe. Only returns
        proxy data.


        **Access Scope:** Reports > Granular Events > Read-Only'
      operationId: getBandwidthByHour
      security:
      - oauthFlow:
        - reports.granularEvents:read
      summary: Get Bandwidth by Hour (All)
      tags:
      - Bandwidth by Hour
  /reports/v2/bandwidth-by-timerange:
    get:
      description: 'List the bandwidth in bytes within the timeframe. Only returns
        proxy data.


        **Access Scope:** Reports > Granular Events > Read-Only'
      operationId: getBandwidthByTimerange
      security:
      - oauthFlow:
        - reports.granularEvents:read
      summary: Get Bandwidth by Timerange (All)
      tags:
      - Bandwidth by Timerange
  /reports/v2/categories:
    get:
      description: 'List the categories.


        **Access Scope:** Reports > Utilities > Read-Only'
      operationId: getCategories
      security:
      - oauthFlow:
        - reports.utilities:read
      summary: Get Categories
      tags:
      - Utility
  /reports/v2/categories-by-hour:
    get:
      description: 'List the activity volume within the timeframe by type of category.


        **Access Scope:** Reports > Granular Events > Read-Only'
      operationId: getRequestsByHourAndCategory
      security:
      - oauthFlow:
        - reports.granularEvents:read
      summary: Get Requests by Hour and Category (All)
      tags:
      - Organization Requests by Hour and Category
  /reports/v2/categories-by-hour/{type}:
    get:
      description: 'List the activity volume for the type of category within the timeframe.


        **Access Scope:** Reports > Granular Events > Read-Only'
      operationId: getRequestsByHourAndCategoryAndType
      security:
      - oauthFlow:
        - reports.granularEvents:read
      summary: Get Requests by Hour and Category
      tags:
      - Organization Requests by Hour and Category
  /reports/v2/categories-by-timerange:
    get:
      description: 'List the activity volume within the timeframe by category.


        **Access Scope:** Reports > Granular Events > Read-Only'
      operationId: getRequestsByTimerangeAndCategory
      security:
      - oauthFlow:
        - reports.granularEvents:read
      summary: Get Requests by Timerange and Category (All)
      tags:
      - Organization Requests by Timerange and Category
  /reports/v2/categories-by-timerange/{type}:
    get:
      description: 'List the activity volume within the timeframe by category.


        **Access Scope:** Reports > Granular Events > Read-Only'
      operationId: getRequestsByTimerangeAndCategoryType
      security:
      - oauthFlow:
        - reports.granularEvents:read
      summary: Get Requests by Timerange and Category
      tags:
      - Organization Requests by Timerange and Category
  /reports/v2/deployment-status:
    get:
      description: 'List the deployment status within the timeframe.


        **Access Scope:** Reports > Granular Events > Read-Only'
      operationId: getDeploymentStatus
      security:
      - oauthFlow:
        - reports.granularEvents:read
      summary: Get Deployment Status
      tags:
      - Deployment Status
  /reports/v2/identities:
    get:
      description: 'List the identities.


        **Access Scope:** Reports > Utilities > Read-Only'
      operationId: getIdentitiesreportsidentities
      security:
      - oauthFlow:
        - reports.utilities:read
      summary: Get Identities
      tags:
      - Utility
    post:
      description: 'Get the identities information by providing a list of identity
        IDs in the request body.


        **Access Scope:** Reports > Utilities > Read-Only'
      operationId: postIdentities
      security:
      - oauthFlow:
        - reports.utilities:read
      summary: Get Identities By IDs
      tags:
      - Utility
  /reports/v2/identities/{identityid}:
    get:
      description: 'Get identity by identity ID.


        **Access Scope:** Reports > Utilities > Read-Only'
      operationId: getIdentity
      security:
      - oauthFlow:
        - reports.utilities:read
      summary: Get Identity
      tags:
      - Utility
  /reports/v2/identity-distribution:
    get:
      description: 'List the number of requests by identity types.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getIdentityDistribution
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Identity Distribution (All)
      tags:
      - Identity Distribution
  /reports/v2/identity-distribution/{type}:
    get:
      description: 'List the number of requests by identity for the type of traffic.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getIdentityDistributionType
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Identity Distribution By Type
      tags:
      - Identity Distribution
  /reports/v2/private-resources/detailed-stats-identities:
    get:
      description: 'Get detailed identity access statistics for a private resource,
        including a list of identities, total hits count,

        and success or blocked count.


        **Access Scope:** Reports > Private Resources > Read-Only'
      operationId: getPrivateResourceDetailedStatsIdentities
      security:
      - oauthFlow:
        - reports.privateResources:read
      summary: Get Private Resource Identities Access Statistics
      tags:
      - Private Resource
  /reports/v2/private-resources/detailed-stats-timerange:
    get:
      description: 'Get the detailed access statistics for a private resource, including
        total hits count and success or blocked count in a series of time ranges.


        **Access Scope:** Reports > Private Resources > Read-Only'
      operationId: getPrivateResourceDetailedStatsTimerange
      security:
      - oauthFlow:
        - reports.privateResources:read
      summary: Get Private Resource Access Statistics
      tags:
      - Private Resource
  /reports/v2/private-resources/summary-stats:
    get:
      description: 'Get summary statistics of the hits count, the number of identities
        that accessed the resources,

        and the last access time for a list of private resource IDs.


        **Access Scope:** Reports > Private Resources > Read-Only'
      operationId: getPrivateResourceStats
      security:
      - oauthFlow:
        - reports.privateResources:read
      summary: Get Private Resource Summary Access Statistics
      tags:
      - Private Resource
  /reports/v2/remote-access-events:
    get:
      description: 'List the events logged by remote access VPN.


        **Access Scope:** Reports > Granular Events > Read-Only'
      operationId: getRemoteAccessEvents
      security:
      - oauthFlow:
        - reports.granularEvents:read
      summary: Get Remote Access Events
      tags:
      - Remote Access
  /reports/v2/requests-by-appconnector:
    get:
      description: 'Get the count of the total requests for each Resource Connector.


        **Access Scope:** Reports > Private Resources > Read-Only'
      operationId: getTotalRequestsForAppConnector
      security:
      - oauthFlow:
        - reports.privateResources:read
      summary: Get Total Requests by Resource Connector
      tags:
      - Requests Resource Connector
  /reports/v2/requests-by-appconnector-group:
    get:
      description: 'Get the count of the total requests for the Resource Connector
        Group.


        **Access Scope:** Reports > Private Resources > Read-Only'
      operationId: getTotalRequestsForAppConnectorGroup
      security:
      - oauthFlow:
        - reports.privateResources:read
      summary: Get Total Requests by Resource Connector Group
      tags:
      - Requests Resource Connector
  /reports/v2/requests-by-hour:
    get:
      description: 'List the activity volume within the timeframe.


        **Access Scope:** Reports > Granular Events > Read-Only'
      operationId: getRequestsByHour
      security:
      - oauthFlow:
        - reports.granularEvents:read
      summary: Get Requests by Hour (All)
      tags:
      - Organization Requests by Hour
  /reports/v2/requests-by-hour/{type}:
    get:
      description: 'List the activity volume within the timeframe.


        **Access Scope:** Reports > Granular Events > Read-Only'
      operationId: getOrganizationRequestsByHour
      security:
      - oauthFlow:
        - reports.granularEvents:read
      summary: Get Requests by Hour
      tags:
      - Organization Requests by Hour
  /reports/v2/requests-by-timerange:
    get:
      description: 'List the activity volume within the timeframe.


        **Access Scope:** Reports > Granular Events > Read-Only'
      operationId: getRequestsByTimerange
      security:
      - oauthFlow:
        - reports.granularEvents:read
      summary: Get Requests by Timerange (All)
      tags:
      - Organization Requests by Timerange
  /reports/v2/requests-by-timerange/{type}:
    get:
      description: 'List the activity volume within the timeframe.


        **Access Scope:** Reports > Granular Events > Read-Only'
      operationId: getRequestsByTimerangeType
      security:
      - oauthFlow:
        - reports.granularEvents:read
      summary: Get Requests by Timerange
      tags:
      - Organization Requests by Timerange
  /reports/v2/requests-summary/appconnector-groups:
    get:
      description: 'Get the summary of the request counts for the Resource Connector
        Groups in the organization.


        **Access Scope:** Reports > Private Resources > Read-Only'
      operationId: getRequestsSummaryForAppConnectorGroups
      security:
      - oauthFlow:
        - reports.privateResources:read
      summary: Get Requests Summary for Resource Connector Groups
      tags:
      - Requests Summary Resource Connector Groups
  /reports/v2/rules-activity:
    get:
      description: 'Get details about events related to the organization''s rules
        including verdict and resource.


        **Access Scope:** Reports > Private Resources > Read-Only'
      operationId: rulesActivity
      security:
      - oauthFlow:
        - reports.privateResources:read
      summary: Get the Rules for the Event Activity
      tags:
      - Rules Activity
  /reports/v2/summaries-by-category:
    get:
      description: 'List the summaries of requests by category.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getSummariesByCategory
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Summaries by Category (All)
      tags:
      - Summaries by Category
  /reports/v2/summaries-by-category/{type}:
    get:
      description: 'List the summaries by category for the type of request.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getSummariesByCategoryType
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Summaries by Category For Type
      tags:
      - Summaries by Category
  /reports/v2/summaries-by-destination:
    get:
      description: 'List the summaries by destination.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getSummariesByDestination
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Summaries by Destination (All)
      tags:
      - Summaries by Destination
  /reports/v2/summaries-by-destination/{type}:
    get:
      description: 'List the summaries by destination for the type of traffic.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getSummariesByDestinationType
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Summaries by Destination For Type
      tags:
      - Summaries by Destination
  /reports/v2/summaries-by-rule/firewall-hitcount:
    get:
      description: 'List the summaries by rule for the policy rule firewall hit count.


        **Access Scope:** Reports > Summaries by rule > Read-Only'
      operationId: getSummariesByRuleFirewallHitcount
      security:
      - oauthFlow:
        - reports.summariesByRule:read
      summary: Get Summaries Rule Firewall Hit Count
      tags:
      - Summaries by Rule
  /reports/v2/summaries-by-rule/hitcount:
    get:
      description: 'List the summaries by rule for the policy rule hit count.


        **Access Scope:** Reports > Summaries by rule > Read-Only'
      operationId: getSummariesByRuleHitcount
      security:
      - oauthFlow:
        - reports.summariesByRule:read
      summary: Get Summaries Rule Hit Count
      tags:
      - Summaries by Rule
  /reports/v2/summaries-by-rule/intrusion:
    get:
      description: 'List the summaries by rule for the intrusion type.


        **Access Scope:** Reports > Summaries by rule > Read-Only'
      operationId: getSummariesByRuleIntrusion
      security:
      - oauthFlow:
        - reports.summariesByRule:read
      summary: Get Summaries Rule Intrusion
      tags:
      - Summaries by Rule
  /reports/v2/summary:
    get:
      description: 'Get the summary report.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getSummary
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Summary (All)
      tags:
      - Summary
  /reports/v2/summary/{type}:
    get:
      description: 'Get the summary of requests by the traffic type.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getSummaryByType
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Summary By Type
      tags:
      - Summary
  /reports/v2/threat-names:
    get:
      description: 'List the threat names.


        **Access Scope:** Reports > Utilities > Read-Only'
      operationId: getThreatNames
      security:
      - oauthFlow:
        - reports.utilities:read
      summary: Get Threat Names
      tags:
      - Utility
  /reports/v2/threat-names/{threatnameid}:
    get:
      description: 'Get the threat name by threat ID.


        **Access Scope:** Reports > Utilities > Read-Only'
      operationId: getThreatName
      security:
      - oauthFlow:
        - reports.utilities:read
      summary: Get Threat Name By Threat ID
      tags:
      - Utility
  /reports/v2/threat-types:
    get:
      description: 'List the threat types.


        **Access Scope:** Reports > Utilities > Read-Only'
      operationId: getThreatTypes
      security:
      - oauthFlow:
        - reports.utilities:read
      summary: Get Threat Types
      tags:
      - Utility
  /reports/v2/threat-types/{threattypeid}:
    get:
      description: 'List the threat types by threat ID.


        **Access Scope:** Reports > Utilities > Read-Only'
      operationId: getThreatType
      security:
      - oauthFlow:
        - reports.utilities:read
      summary: Get Threat Type By Threat ID
      tags:
      - Utility
  /reports/v2/top-categories:
    get:
      description: 'List the categories that received the greatest number of requests.

        Order the number of requests in descending order.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getTopCategories
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Top Categories (All)
      tags:
      - Top Categories
  /reports/v2/top-categories/{type}:
    get:
      description: 'List the categories for the type of traffic that received the
        greatest number of requests.

        Order the number of requests in descending order.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getTopCategoriesType
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Top Categories By Type
      tags:
      - Top Categories
  /reports/v2/top-destinations:
    get:
      description: 'List the destinations by the number of requests made to this destination.

        Return the results in descending order.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getTopDestinations
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Top Destinations
      tags:
      - Top Destinations
  /reports/v2/top-destinations/{type}:
    get:
      description: 'List the destinations by type of destination and the number of
        requests made

        to this destination. Return the collection in descending order.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getTopDestinationsType
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Top Destinations By Type
      tags:
      - Top Destinations
  /reports/v2/top-dns-query-types:
    get:
      description: 'List the top types of DNS query.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getTopDNSQueryTypes
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Top DNS Query Types
      tags:
      - Top DNS Query Types
  /reports/v2/top-eventtypes:
    get:
      description: 'List the top event types by the number of requests made for each
        type of event.

        Order the number of requests in descending order.

        The valid event types are: `domain_security`, `domain_integration`,

        `url_security`, `url_integration`, `cisco_amp`, and `antivirus`.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getTopEventTypes
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Top Event Types (All)
      tags:
      - Top Event Types
  /reports/v2/top-files:
    get:
      description: 'List the top files within the timeframe. Only returns proxy data.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getTopFilesProxy
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Top Files (Proxy)
      tags:
      - Top Files
  /reports/v2/top-identities:
    get:
      description: 'List the identities by the number of requests made, sorted in
        descending order.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getTopIdentities
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Top Identities (All)
      tags:
      - Top Identities
  /reports/v2/top-identities/{type}:
    get:
      description: 'List the identities for the specific traffic type by the number
        of requests.

        Sort the results in descending order.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getTopIdentitiesType
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Top Identities
      tags:
      - Top Identities
  /reports/v2/top-ips:
    get:
      description: 'List the top IP addresses.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getTopIps
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Top IPs
      tags:
      - Top IPs
  /reports/v2/top-ips/internal:
    get:
      description: 'List the top internal IP addresses.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getTopIpsInternal
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Top IPs Internal
      tags:
      - Top IPs
  /reports/v2/top-resources:
    get:
      description: 'List all resources in descending order. Order the collection by
        the number of requests to get the resources.


        **Access Scope:** Reports > Private Resources > Read-Only'
      operationId: getTopResources
      security:
      - oauthFlow:
        - reports.privateResources:read
      summary: Get Top Resources (All)
      tags:
      - Top Resources
  /reports/v2/top-resources/{type}:
    get:
      description: 'List the resources for the type of activity in descending order.

        Order the collection by the number of requests to get the resources.


        **Access Scope:** Reports > Private Resources > Read-Only'
      operationId: getTopResourcesType
      security:
      - oauthFlow:
        - reports.privateResources:read
      summary: Get Top Resources by Type
      tags:
      - Top Resources
  /reports/v2/top-threat-types:
    get:
      description: 'List the top types of threat within the timeframe. Returns both
        DNS and proxy data.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getTopThreatTypes
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Top Threat Types (All)
      tags:
      - Top Threat Types
  /reports/v2/top-threat-types/{type}:
    get:
      description: 'List the top threat-types within the timeframe.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getTopThreatTypesByType
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Top Threat Types By Type
      tags:
      - Top Threat Types
  /reports/v2/top-threats:
    get:
      description: 'Get the top threats within the timeframe. Returns both DNS and
        proxy data.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getTopThreats
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Top Threats (All)
      tags:
      - Top Threats
  /reports/v2/top-threats/{type}:
    get:
      description: 'Get the top threats within the timeframe.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getTopThreatsByType
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Top Threats (By Type)
      tags:
      - Top Threats
  /reports/v2/top-urls:
    get:
      description: 'List the top number of URLs that are requested for a certain domain.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getTopUrls
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Top URLs
      tags:
      - Top Destinations
  /reports/v2/total-requests:
    get:
      description: 'Get the count of the total requests.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getTotalRequests
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Total Requests (All)
      tags:
      - Total Requests
  /reports/v2/total-requests/{type}:
    get:
      description: 'Get the count of the total requests for the request type.


        **Access Scope:** Reports > Aggregations > Read-Only'
      operationId: getTotalRequestsByType
      security:
      - oauthFlow:
        - reports.aggregations:read
      summary: Get Total Requests (By Type)
      tags:
      - Total Requests
  /reports/v2/unique-resources:
    get:
      description: 'Get a count of the number of unique resources.


        **Access Scope:** Reports > Private Resources > Read-Only'
      operationId: getUniqueResources
      security:
      - oauthFlow:
        - reports.privateResources:read
      summary: Get Unique Resources (All)
      tags:
      - Unique Resources
  /reports/v2/usage/metrics:
    get:
      description: List the usage metrics for the organization.
      operationId: getUsageMetrics
      security:
      - oauthFlow:
        - reports.usage.metrics:read
      summary: List Usage Metrics
      tags:
      - Usage Metrics
components:
  securitySchemes:
    apiUsageApiOauthFlow:
      description: Client credential flow
      flows:
        clientCredentials:
          scopes:
            reports.apiusage:read: Read the API Usage reports
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    appDiscoveryOauthFlow:
      description: client credential flow
      flows:
        clientCredentials:
          scopes:
            reports.appDiscovery:read: Read reports app discovery
            reports.appDiscovery:write: Write reports app discovery
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    applicationCategoriesOauthFlow:
      description: The client credential flow.
      flows:
        clientCredentials:
          scopes:
            policies.applicationCategories:read: Read Application Category settings
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    applicationListsOauthFlow:
      description: The client credential flow.
      flows:
        clientCredentials:
          scopes:
            policies.applicationlists:read: Read policies application lists
            policies.applicationlists:write: Write policies application lists
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    contentCategoriesOauthFlow:
      description: The client credential flow.
      flows:
        clientCredentials:
          scopes:
            policies.contentCategories:read: Read Content Category settings
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    destinationListsOauthFlow:
      description: client credential flow
      flows:
        clientCredentials:
          scopes:
            policies.destinationLists:read: Read policies destination lists
            policies.destinationLists:write: Write policies destination lists
            policies.destinations:read: Read policies destinations
            policies.destinations:write: Write policies destinations
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    dnsForwardersOauthFlow:
      description: Client credential flow.
      flows:
        clientCredentials:
          scopes:
            deployments.dnsforwarders:read: Read deployments DNS forwarders
            deployments.dnsforwarders:write: Write deployments DNS forwarders
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    http:
      scheme: basic
      type: http
    identitiesRegistrationOauthFlow:
      description: The client credential flow.
      flows:
        clientCredentials:
          scopes:
            deployments.identities:read: Read the identity endpoint or security group
              tag.
            deployments.identities:write: Update the identity endpoint or security
              group tag.
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    internalDomainsOauthFlow:
      description: The client credential flow.
      flows:
        clientCredentials:
          scopes:
            deployments.internaldomains:read: Read deployments internal domains
            deployments.internaldomains:write: Write deployments internal domains
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    investigateOauthFlow:
      description: The client credential flow.
      flows:
        clientCredentials:
          scopes:
            investigate.bulk:read: Investigate bulk read access
            investigate.investigate:read: Investigate read access
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    ipsProfilesOauthFlow:
      description: The client credential flow.
      flows:
        clientCredentials:
          scopes:
            policies.ipsconfig:read: Read Intrusion Prevention System profiles
            policies.ipsconfig:write: Write Intrusion Prevention System profiles
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    keyAdminOauthFlow:
      description: client credential flow
      flows:
        clientCredentials:
          scopes:
            admin.apikeys:create: Create admin API keys
            admin.apikeys:delete: Delete admin API keys
            admin.apikeys:read: Read admin API keys
            admin.apikeys:refresh: Refresh admin API keys
            admin.apikeys:update: Update admin API keys
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    meteringOauthFlow:
      description: client credential flow
      flows:
        clientCredentials:
          scopes:
            reports.usage.metrics:read: Get usage data
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    networkDevicesOauthFlow:
      description: client credential flow
      flows:
        clientCredentials:
          scopes:
            deployments.networkdevices:read: Read deployments network devices
            deployments.networkdevices:write: Write deployments network devices
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    networkOauthFlow:
      description: Client credential flow.
      flows:
        clientCredentials:
          scopes:
            policies.objects.networkObjectGroups:read: Read the Network Object Group
              resources
            policies.objects.networkObjectGroups:write: Write the Network Object Group
              resources
            policies.objects.networkObjects:read: Read the Network Object resources
            policies.objects.networkObjects:write: Write the Network Object resources
            policies.objects.serviceObjectGroups:read: Read the Service Object Groups
              resources
            policies.objects.serviceObjectGroups:write: Write the Service Object Group
              resources
            policies.objects.serviceObjects:read: Read the Service Object resources
            policies.objects.serviceObjects:write: Write the Service Object resources
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    networkTunnelGroupsOauthFlow:
      description: client credential flow
      flows:
        clientCredentials:
          scopes:
            deployments.networktunnelgroups:read: Read network tunnel groups deployments
            deployments.networktunnelgroups:write: Write network tunnel groups deployments
            deployments.regions:read: Read regions for network tunnel groups deployments
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    networksOauthFlow:
      description: The client credential flow.
      flows:
        clientCredentials:
          scopes:
            deployments.networks:read: Read deployments networks
            deployments.networks:write: Write deployments networks
          tokenUrl: https://api.umbrella.com/auth/v2/token
      type: oauth2
    oauthFlow:
      description: client credential flow
      flows:
        clientCredentials:
          scopes:
            deployments.internalnetworks:read: Read deployments internal networks
            deployments.internalnetworks:write: Write deployments internal networks
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    policyRulesOauthFlow:
      description: The client credential flow.
      flows:
        clientCredentials:
          scopes:
            policies.rules:read: Read policies access rules
            policies.rules:write: Write policies access rules
            policies.settings:read: Read policies global rule settings
            policies.settings:write: Write policies global rule settings
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    privateResourcesOauthFlow:
      description: The client credential flow.
      flows:
        clientCredentials:
          scopes:
            policies.privateresourcegroups:read: Read the Private Resource Groups
              resources
            policies.privateresourcegroups:write: Write the Private Resource Groups
              resources
            policies.privateresources:read: Read the Private Resources resources
            policies.privateresources:write: Write the Private Resources resources
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    reportingOauthFlow:
      description: client credential flow
      flows:
        clientCredentials:
          scopes:
            reports.aggregations:read: Read reports aggregations
            reports.granularEvents:read: Read reports granular events
            reports.privateResources:read: Read reports for the private resources
            reports.summariesByRule:read: Read reports for the summaries of the rule
            reports.utilities:read: Read reports utilities
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    resourceConnectorGroupsOauthFlow:
      description: Client credential flow.
      flows:
        clientCredentials:
          scopes:
            deployments.resourceconnectors:read: Read the Resource Connector Group
              or Connector resources
            deployments.resourceconnectors:write: Write the Resource Connector Group
              or Connector resources
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    roamingComputersOauthFlow:
      description: Client credential flow.
      flows:
        clientCredentials:
          scopes:
            deployments.roamingcomputers:read: Read deployments roaming computers
            deployments.roamingcomputers:write: Write deployments roaming computers
            deployments.roamingcomputersOrgInfo:read: Read deployments roaming computers
              and OrgInfo properties
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    s3BucketOauthFlow:
      description: The client credential flow.
      flows:
        clientCredentials:
          scopes:
            admin.iam:write: Write the Cisco-managed S3 bucket key.
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    securityProfilesOauthFlow:
      description: The client credential flow.
      flows:
        clientCredentials:
          scopes:
            policies.securityProfiles:read: Read Security Profiles
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    sitesOauthFlow:
      description: Client credential flow.
      flows:
        clientCredentials:
          scopes:
            deployments.sites:read: Read deployments Sites
            deployments.sites:write: Write deployments Sites
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    tenantControlsProfilesOauthFlow:
      description: The client credential flow.
      flows:
        clientCredentials:
          scopes:
            policies.tenantControlsProfiles:read: Read Tenant Controls Profiles
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    thirdPartyIntegrationsOauthFlow:
      description: The client credential flow.
      flows:
        clientCredentials:
          scopes:
            admin.integrations:read: Read integrations
            admin.integrations:write: Update, delete integrations
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    threatIntelligenceFeedsOauthFlow:
      description: The client credential flow.
      flows:
        clientCredentials:
          scopes:
            policies.feeds:read: Read policies security threat feeds
            policies.feeds:write: Write policies security threat feeds
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    vpnUserConnectionsOauthFlow:
      description: The client credential flow.
      flows:
        clientCredentials:
          scopes:
            admin.vpn:read: Read the remote access VPN user connections.
            admin.vpn:write: Update the remote access VPN user connections.
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
    zeroTrustUserDevicesOauthFlow:
      description: The client credential flow.
      flows:
        clientCredentials:
          scopes:
            admin.ztna.certificates:read: Read the certificate metadata for the users.
            admin.ztna.devices:read: Read the certificate metadata for the user device
            admin.ztna.enrollment:write: Revoke the certificates for the user device
            admin.ztna.users:read: Read the user summaries.
          tokenUrl: https://api.sse.cisco.com/auth/v2/token
      type: oauth2
