# Copyright 2025 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202510221109
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from datetime import date
from pydantic import Field, StrictInt, StrictStr, field_validator
from typing import List, Optional
from typing_extensions import Annotated
from secure_access.models.get_identities200_response import GetIdentities200Response
from secure_access.models.protocol_identity_list import ProtocolIdentityList
from secure_access.models.update_identities200_response import UpdateIdentities200Response
from secure_access.models.update_identities_request_inner import UpdateIdentitiesRequestInner

from secure_access.api_client import ApiClient, RequestSerialized
from secure_access.api_response import ApiResponse
from secure_access.rest import RESTResponseType


class IdentitiesApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_identities(
        self,
        type: Annotated[StrictStr, Field(description="Use `device` to query the collection for the identity endpoints in the organization. Use `securityGroupTag` to query the collection for the security group tags in the organization.")],
        label: Annotated[Optional[StrictStr], Field(description="The descriptive name of the identity endpoint or security group tag (SGT).")] = None,
        offset: Annotated[Optional[StrictInt], Field(description="The place to start reading in the collection. The default offset is `0`.")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=250, strict=True, ge=1)]], Field(description="The number of items to return in the page. The default limit is `100`.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> GetIdentities200Response:
        """List Identities

        Get the list of identity endpoints or security group tags (SGTs) for the identities in the organization.

        :param type: Use `device` to query the collection for the identity endpoints in the organization. Use `securityGroupTag` to query the collection for the security group tags in the organization. (required)
        :type type: str
        :param label: The descriptive name of the identity endpoint or security group tag (SGT).
        :type label: str
        :param offset: The place to start reading in the collection. The default offset is `0`.
        :type offset: int
        :param limit: The number of items to return in the page. The default limit is `100`.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_identities_serialize(
            type=type,
            label=label,
            offset=offset,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetIdentities200Response",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '405': None,
            '500': "IdentitiesRegistration500Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_identities_with_http_info(
        self,
        type: Annotated[StrictStr, Field(description="Use `device` to query the collection for the identity endpoints in the organization. Use `securityGroupTag` to query the collection for the security group tags in the organization.")],
        label: Annotated[Optional[StrictStr], Field(description="The descriptive name of the identity endpoint or security group tag (SGT).")] = None,
        offset: Annotated[Optional[StrictInt], Field(description="The place to start reading in the collection. The default offset is `0`.")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=250, strict=True, ge=1)]], Field(description="The number of items to return in the page. The default limit is `100`.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[GetIdentities200Response]:
        """List Identities

        Get the list of identity endpoints or security group tags (SGTs) for the identities in the organization.

        :param type: Use `device` to query the collection for the identity endpoints in the organization. Use `securityGroupTag` to query the collection for the security group tags in the organization. (required)
        :type type: str
        :param label: The descriptive name of the identity endpoint or security group tag (SGT).
        :type label: str
        :param offset: The place to start reading in the collection. The default offset is `0`.
        :type offset: int
        :param limit: The number of items to return in the page. The default limit is `100`.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_identities_serialize(
            type=type,
            label=label,
            offset=offset,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetIdentities200Response",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '405': None,
            '500': "IdentitiesRegistration500Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_identities_without_preload_content(
        self,
        type: Annotated[StrictStr, Field(description="Use `device` to query the collection for the identity endpoints in the organization. Use `securityGroupTag` to query the collection for the security group tags in the organization.")],
        label: Annotated[Optional[StrictStr], Field(description="The descriptive name of the identity endpoint or security group tag (SGT).")] = None,
        offset: Annotated[Optional[StrictInt], Field(description="The place to start reading in the collection. The default offset is `0`.")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=250, strict=True, ge=1)]], Field(description="The number of items to return in the page. The default limit is `100`.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List Identities

        Get the list of identity endpoints or security group tags (SGTs) for the identities in the organization.

        :param type: Use `device` to query the collection for the identity endpoints in the organization. Use `securityGroupTag` to query the collection for the security group tags in the organization. (required)
        :type type: str
        :param label: The descriptive name of the identity endpoint or security group tag (SGT).
        :type label: str
        :param offset: The place to start reading in the collection. The default offset is `0`.
        :type offset: int
        :param limit: The number of items to return in the page. The default limit is `100`.
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_identities_serialize(
            type=type,
            label=label,
            offset=offset,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetIdentities200Response",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '405': None,
            '500': "IdentitiesRegistration500Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_identities_serialize(
        self,
        type,
        label,
        offset,
        limit,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if type is not None:
            _path_params['type'] = type
        # process the query parameters
        if label is not None:
            
            _query_params.append(('label', label))
            
        if offset is not None:
            
            _query_params.append(('offset', offset))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'text/plain'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'oauthFlow'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/deployments/v2/identities/registrations/{type}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_protocol_identities(
        self,
        protocol_id: Annotated[StrictStr, Field(description="The ID of the protocol.")],
        var_date: Annotated[Optional[date], Field(description="Specify a date to search for data within a twenty-four hour time period. If you do not provide a date, the last 90 days period is used to query the collection.")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="The maximum number of items to return in the collection.")] = None,
        offset: Annotated[Optional[StrictInt], Field(description="The number of items to skip before starting to collect the result set.")] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Specify the name of a field to sort the application identities.")] = None,
        order: Annotated[Optional[StrictStr], Field(description="Specify the order to sort the collection. Valid values are: `asc` (ascending) or `desc` (descending).")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ProtocolIdentityList:
        """List Protocol Identities

        List identities for a specific protocol.

        :param protocol_id: The ID of the protocol. (required)
        :type protocol_id: str
        :param var_date: Specify a date to search for data within a twenty-four hour time period. If you do not provide a date, the last 90 days period is used to query the collection.
        :type var_date: date
        :param limit: The maximum number of items to return in the collection.
        :type limit: int
        :param offset: The number of items to skip before starting to collect the result set.
        :type offset: int
        :param sort: Specify the name of a field to sort the application identities.
        :type sort: str
        :param order: Specify the order to sort the collection. Valid values are: `asc` (ascending) or `desc` (descending).
        :type order: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_protocol_identities_serialize(
            protocol_id=protocol_id,
            var_date=var_date,
            limit=limit,
            offset=offset,
            sort=sort,
            order=order,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ProtocolIdentityList",
            '400': "Error",
            '401': "Error",
            '403': "Error",
            '404': "Error",
            '500': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_protocol_identities_with_http_info(
        self,
        protocol_id: Annotated[StrictStr, Field(description="The ID of the protocol.")],
        var_date: Annotated[Optional[date], Field(description="Specify a date to search for data within a twenty-four hour time period. If you do not provide a date, the last 90 days period is used to query the collection.")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="The maximum number of items to return in the collection.")] = None,
        offset: Annotated[Optional[StrictInt], Field(description="The number of items to skip before starting to collect the result set.")] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Specify the name of a field to sort the application identities.")] = None,
        order: Annotated[Optional[StrictStr], Field(description="Specify the order to sort the collection. Valid values are: `asc` (ascending) or `desc` (descending).")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ProtocolIdentityList]:
        """List Protocol Identities

        List identities for a specific protocol.

        :param protocol_id: The ID of the protocol. (required)
        :type protocol_id: str
        :param var_date: Specify a date to search for data within a twenty-four hour time period. If you do not provide a date, the last 90 days period is used to query the collection.
        :type var_date: date
        :param limit: The maximum number of items to return in the collection.
        :type limit: int
        :param offset: The number of items to skip before starting to collect the result set.
        :type offset: int
        :param sort: Specify the name of a field to sort the application identities.
        :type sort: str
        :param order: Specify the order to sort the collection. Valid values are: `asc` (ascending) or `desc` (descending).
        :type order: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_protocol_identities_serialize(
            protocol_id=protocol_id,
            var_date=var_date,
            limit=limit,
            offset=offset,
            sort=sort,
            order=order,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ProtocolIdentityList",
            '400': "Error",
            '401': "Error",
            '403': "Error",
            '404': "Error",
            '500': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_protocol_identities_without_preload_content(
        self,
        protocol_id: Annotated[StrictStr, Field(description="The ID of the protocol.")],
        var_date: Annotated[Optional[date], Field(description="Specify a date to search for data within a twenty-four hour time period. If you do not provide a date, the last 90 days period is used to query the collection.")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="The maximum number of items to return in the collection.")] = None,
        offset: Annotated[Optional[StrictInt], Field(description="The number of items to skip before starting to collect the result set.")] = None,
        sort: Annotated[Optional[StrictStr], Field(description="Specify the name of a field to sort the application identities.")] = None,
        order: Annotated[Optional[StrictStr], Field(description="Specify the order to sort the collection. Valid values are: `asc` (ascending) or `desc` (descending).")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List Protocol Identities

        List identities for a specific protocol.

        :param protocol_id: The ID of the protocol. (required)
        :type protocol_id: str
        :param var_date: Specify a date to search for data within a twenty-four hour time period. If you do not provide a date, the last 90 days period is used to query the collection.
        :type var_date: date
        :param limit: The maximum number of items to return in the collection.
        :type limit: int
        :param offset: The number of items to skip before starting to collect the result set.
        :type offset: int
        :param sort: Specify the name of a field to sort the application identities.
        :type sort: str
        :param order: Specify the order to sort the collection. Valid values are: `asc` (ascending) or `desc` (descending).
        :type order: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_protocol_identities_serialize(
            protocol_id=protocol_id,
            var_date=var_date,
            limit=limit,
            offset=offset,
            sort=sort,
            order=order,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ProtocolIdentityList",
            '400': "Error",
            '401': "Error",
            '403': "Error",
            '404': "Error",
            '500': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_protocol_identities_serialize(
        self,
        protocol_id,
        var_date,
        limit,
        offset,
        sort,
        order,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if protocol_id is not None:
            _path_params['protocolId'] = protocol_id
        # process the query parameters
        if var_date is not None:
            if isinstance(var_date, date):
                _query_params.append(
                    (
                        'date',
                        var_date.strftime(
                            self.api_client.configuration.date_format
                        )
                    )
                )
            else:
                _query_params.append(('date', var_date))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if offset is not None:
            
            _query_params.append(('offset', offset))
            
        if sort is not None:
            
            _query_params.append(('sort', sort))
            
        if order is not None:
            
            _query_params.append(('order', order))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'oauthFlow'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/reports/v2/appDiscovery/protocols/{protocolId}/identities',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def update_identities(
        self,
        type: Annotated[StrictStr, Field(description="Use `device` to query the collection for the identity endpoints in the organization. Use `securityGroupTag` to query the collection for the security group tags in the organization.")],
        update_identities_request_inner: Annotated[List[UpdateIdentitiesRequestInner], Field(max_length=250)],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> UpdateIdentities200Response:
        """Update Identities

        * Use the `PUT` operation to add a list of identity devices or security group tags (SGTs) in the organization. For each API operation, you can add 1–250 identity devices   or security group tags. * Use the `PUT` operation to modify the properties of the identities registered in the organization.   When you set the `status` field of an identity endpoint or security group tag to `inactive`, Secure Access makes the identity inactive in the organization   and the identity is not managed or protected by the configured access rules and security controls in the Access policy.

        :param type: Use `device` to query the collection for the identity endpoints in the organization. Use `securityGroupTag` to query the collection for the security group tags in the organization. (required)
        :type type: str
        :param update_identities_request_inner: (required)
        :type update_identities_request_inner: List[UpdateIdentitiesRequestInner]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._update_identities_serialize(
            type=type,
            update_identities_request_inner=update_identities_request_inner,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "UpdateIdentities200Response",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '405': None,
            '500': "IdentitiesRegistration500Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def update_identities_with_http_info(
        self,
        type: Annotated[StrictStr, Field(description="Use `device` to query the collection for the identity endpoints in the organization. Use `securityGroupTag` to query the collection for the security group tags in the organization.")],
        update_identities_request_inner: Annotated[List[UpdateIdentitiesRequestInner], Field(max_length=250)],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[UpdateIdentities200Response]:
        """Update Identities

        * Use the `PUT` operation to add a list of identity devices or security group tags (SGTs) in the organization. For each API operation, you can add 1–250 identity devices   or security group tags. * Use the `PUT` operation to modify the properties of the identities registered in the organization.   When you set the `status` field of an identity endpoint or security group tag to `inactive`, Secure Access makes the identity inactive in the organization   and the identity is not managed or protected by the configured access rules and security controls in the Access policy.

        :param type: Use `device` to query the collection for the identity endpoints in the organization. Use `securityGroupTag` to query the collection for the security group tags in the organization. (required)
        :type type: str
        :param update_identities_request_inner: (required)
        :type update_identities_request_inner: List[UpdateIdentitiesRequestInner]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._update_identities_serialize(
            type=type,
            update_identities_request_inner=update_identities_request_inner,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "UpdateIdentities200Response",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '405': None,
            '500': "IdentitiesRegistration500Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def update_identities_without_preload_content(
        self,
        type: Annotated[StrictStr, Field(description="Use `device` to query the collection for the identity endpoints in the organization. Use `securityGroupTag` to query the collection for the security group tags in the organization.")],
        update_identities_request_inner: Annotated[List[UpdateIdentitiesRequestInner], Field(max_length=250)],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Update Identities

        * Use the `PUT` operation to add a list of identity devices or security group tags (SGTs) in the organization. For each API operation, you can add 1–250 identity devices   or security group tags. * Use the `PUT` operation to modify the properties of the identities registered in the organization.   When you set the `status` field of an identity endpoint or security group tag to `inactive`, Secure Access makes the identity inactive in the organization   and the identity is not managed or protected by the configured access rules and security controls in the Access policy.

        :param type: Use `device` to query the collection for the identity endpoints in the organization. Use `securityGroupTag` to query the collection for the security group tags in the organization. (required)
        :type type: str
        :param update_identities_request_inner: (required)
        :type update_identities_request_inner: List[UpdateIdentitiesRequestInner]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._update_identities_serialize(
            type=type,
            update_identities_request_inner=update_identities_request_inner,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "UpdateIdentities200Response",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '405': None,
            '500': "IdentitiesRegistration500Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _update_identities_serialize(
        self,
        type,
        update_identities_request_inner,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'UpdateIdentitiesRequestInner': '',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if type is not None:
            _path_params['type'] = type
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if update_identities_request_inner is not None:
            _body_params = update_identities_request_inner


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'text/plain'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'oauthFlow'
        ]

        return self.api_client.param_serialize(
            method='PUT',
            resource_path='/deployments/v2/identities/registrations/{type}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


