# Copyright 2025 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202510221109
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AttributeName(str, Enum):
    """
    The name of the attribute.
    """

    """
    allowed enum values
    """
    UMBRELLA_DOT_SOURCE_DOT_ALL = 'umbrella.source.all'
    UMBRELLA_DOT_SOURCE_DOT_NETWORK_OBJECT_IDS = 'umbrella.source.networkObjectIds'
    UMBRELLA_DOT_SOURCE_DOT_NETWORK_OBJECT_GROUP_IDS = 'umbrella.source.networkObjectGroupIds'
    UMBRELLA_DOT_SOURCE_DOT_IDENTITY_TYPE_IDS = 'umbrella.source.identity_type_ids'
    UMBRELLA_DOT_SOURCE_DOT_IP_ADDRESS = 'umbrella.source.ip_address'
    UMBRELLA_DOT_SOURCE_DOT_IDENTITY_IDS = 'umbrella.source.identity_ids'
    UMBRELLA_DOT_DESTINATION_DOT_ALL = 'umbrella.destination.all'
    UMBRELLA_DOT_DESTINATION_DOT_NETWORK_OBJECT_IDS = 'umbrella.destination.networkObjectIds'
    UMBRELLA_DOT_DESTINATION_DOT_NETWORK_OBJECT_GROUP_IDS = 'umbrella.destination.networkObjectGroupIds'
    UMBRELLA_DOT_DESTINATION_DOT_SERVICE_OBJECT_IDS = 'umbrella.destination.serviceObjectIds'
    UMBRELLA_DOT_DESTINATION_DOT_SERVICE_OBJECT_GROUP_IDS = 'umbrella.destination.serviceObjectGroupIds'
    UMBRELLA_DOT_DESTINATION_DOT_APPLICATION_IDS = 'umbrella.destination.application_ids'
    UMBRELLA_DOT_DESTINATION_DOT_APPLICATION_LIST_IDS = 'umbrella.destination.application_list_ids'
    UMBRELLA_DOT_DESTINATION_DOT_PRIVATE_APPLICATION_IDS = 'umbrella.destination.private_application_ids'
    UMBRELLA_DOT_DESTINATION_DOT_PRIVATE_APPLICATION_GROUP_IDS = 'umbrella.destination.private_application_group_ids'
    UMBRELLA_DOT_DESTINATION_DOT_CATEGORY_IDS = 'umbrella.destination.category_ids'
    UMBRELLA_DOT_DESTINATION_DOT_CATEGORY_LIST_IDS = 'umbrella.destination.category_list_ids'
    UMBRELLA_DOT_DESTINATION_DOT_DESTINATION_LIST_IDS = 'umbrella.destination.destination_list_ids'
    UMBRELLA_DOT_DESTINATION_DOT_LOGICAL_OPERATOR = 'umbrella.destination.logical_operator'
    UMBRELLA_DOT_DESTINATION_DOT_GEOLOCATIONS = 'umbrella.destination.geolocations'
    UMBRELLA_DOT_DESTINATION_DOT_PRIVATE_RESOURCE_IDS = 'umbrella.destination.private_resource_ids'
    UMBRELLA_DOT_DESTINATION_DOT_IP_ADDRESS = 'umbrella.destination.ip_address'
    UMBRELLA_DOT_DESTINATION_DOT_PORT = 'umbrella.destination.port'
    UMBRELLA_DOT_DESTINATION_DOT_NETWORK_PROTOCOL = 'umbrella.destination.network_protocol'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AttributeName from a JSON string"""
        return cls(json.loads(json_str))


