# Copyright 2025 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202510221109
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class CreateNetworkRequest(BaseModel):
    """
    CreateNetworkRequest
    """ # noqa: E501
    ip_address: Optional[StrictStr] = Field(default=None, description="The IP address of the network.", alias="ipAddress")
    is_dynamic: StrictBool = Field(description="Specifies whether the IP is dynamic.", alias="isDynamic")
    name: Annotated[str, Field(min_length=1, strict=True, max_length=50)] = Field(description="The name of the network.")
    prefix_length: Annotated[int, Field(le=32, strict=True, ge=29)] = Field(description="The length of the prefix. Set a prefix length that is greater than 28 and less than 33.", alias="prefixLength")
    status: Annotated[str, Field(strict=True)] = Field(description="The status of the network.")
    __properties: ClassVar[List[str]] = ["ipAddress", "isDynamic", "name", "prefixLength", "status"]

    @field_validator('status')
    def status_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^(OPEN|CLOSED)$", value):
            raise ValueError(r"must validate the regular expression /^(OPEN|CLOSED)$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateNetworkRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateNetworkRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ipAddress": obj.get("ipAddress"),
            "isDynamic": obj.get("isDynamic"),
            "name": obj.get("name"),
            "prefixLength": obj.get("prefixLength"),
            "status": obj.get("status")
        })
        return _obj


