# Copyright 2025 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202510221109
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CredentialType(str, Enum):
    """
    The authentication method used to obtain the credential.
    """

    """
    allowed enum values
    """
    GOOGLE_MINUS_SERVICE_MINUS_ACCOUNT = 'google-service-account'
    BASIC_MINUS_AUTH = 'basic-auth'
    PIAM_MINUS_TOKEN = 'piam-token'
    IROH_MINUS_TOKEN = 'iroh-token'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CredentialType from a JSON string"""
        return cls(json.loads(json_str))


