# Copyright 2025 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202510221109
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DataStorage(str, Enum):
    """
    The form of the stored data. Valid values are: `noStorage`, `structured`, `unstructured`, or `na`.
    """

    """
    allowed enum values
    """
    NOSTORAGE = 'noStorage'
    STRUCTURED = 'structured'
    UNSTRUCTURED = 'unstructured'
    NA = 'na'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DataStorage from a JSON string"""
        return cls(json.loads(json_str))


