# Copyright 2025 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202510221109
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DestinationListsBundleTypeId(int, Enum):
    """
    The type of the destination list. In your policy rules, the system applies security controls to your destination lists. **Note:** When you create a destination list, set the `bundleTypeId` to `2`.
    """

    """
    allowed enum values
    """
    NUMBER_2 = 2

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DestinationListsBundleTypeId from a JSON string"""
        return cls(json.loads(json_str))


