# Copyright 2025 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202510221109
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from secure_access.models.credential import Credential
from secure_access.models.integration_status import IntegrationStatus
from secure_access.models.integration_type import IntegrationType
from secure_access.models.intune_config import IntuneConfig
from secure_access.models.jamf_config import JamfConfig
from secure_access.models.webhook_config import WebhookConfig
from typing import Optional, Set
from typing_extensions import Self

class Integration(BaseModel):
    """
    The properties of the integrated third-party application.
    """ # noqa: E501
    created_at: datetime = Field(description="The date and time when the system created the integration.", alias="createdAt")
    created_by: StrictStr = Field(description="The username of the administrator who created the integration.", alias="createdBy")
    created_from_ip: StrictStr = Field(description="The IP address of the device or network where the integration was created.", alias="createdFromIp")
    credentials: Optional[List[Credential]] = Field(default=None, description="The list of credentials associated with the integration.")
    href: StrictStr = Field(description="The URL for the integration.")
    intune_config: Optional[IntuneConfig] = Field(default=None, alias="intuneConfig")
    jamf_config: Optional[JamfConfig] = Field(default=None, alias="jamfConfig")
    name: Annotated[str, Field(min_length=1, strict=True, max_length=250)] = Field(description="The name of the integration.")
    region: Optional[StrictStr] = Field(default=None, description="The region where the system deployed the integration.")
    status: IntegrationStatus
    tags: Optional[List[StrictStr]] = Field(default=None, description="The list of tags associated with the integration.")
    type: IntegrationType
    updated_from_ip: Optional[StrictStr] = Field(default=None, description="The IP address of the device or network where the integration was last updated.", alias="updatedFromIp")
    webhook_config: Optional[WebhookConfig] = Field(default=None, alias="webhookConfig")
    __properties: ClassVar[List[str]] = ["createdAt", "createdBy", "createdFromIp", "credentials", "href", "intuneConfig", "jamfConfig", "name", "region", "status", "tags", "type", "updatedFromIp", "webhookConfig"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Integration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in credentials (list)
        _items = []
        if self.credentials:
            for _item_credentials in self.credentials:
                if _item_credentials:
                    _items.append(_item_credentials.to_dict())
            _dict['credentials'] = _items
        # override the default output from pydantic by calling `to_dict()` of intune_config
        if self.intune_config:
            _dict['intuneConfig'] = self.intune_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of jamf_config
        if self.jamf_config:
            _dict['jamfConfig'] = self.jamf_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of webhook_config
        if self.webhook_config:
            _dict['webhookConfig'] = self.webhook_config.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Integration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "createdAt": obj.get("createdAt"),
            "createdBy": obj.get("createdBy"),
            "createdFromIp": obj.get("createdFromIp"),
            "credentials": [Credential.from_dict(_item) for _item in obj["credentials"]] if obj.get("credentials") is not None else None,
            "href": obj.get("href"),
            "intuneConfig": IntuneConfig.from_dict(obj["intuneConfig"]) if obj.get("intuneConfig") is not None else None,
            "jamfConfig": JamfConfig.from_dict(obj["jamfConfig"]) if obj.get("jamfConfig") is not None else None,
            "name": obj.get("name"),
            "region": obj.get("region"),
            "status": obj.get("status"),
            "tags": obj.get("tags"),
            "type": obj.get("type"),
            "updatedFromIp": obj.get("updatedFromIp"),
            "webhookConfig": WebhookConfig.from_dict(obj["webhookConfig"]) if obj.get("webhookConfig") is not None else None
        })
        return _obj


