# Copyright 2025 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202510221109
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class NetworkObject(BaseModel):
    """
    The properties of the Network resource.
    """ # noqa: E501
    created_at: datetime = Field(description="The date and time (timestamp) when the network was created.", alias="createdAt")
    ip_address: StrictStr = Field(description="The IP address of the network.", alias="ipAddress")
    is_dynamic: StrictBool = Field(description="Specifies whether the network has a dynamic IP.", alias="isDynamic")
    is_verified: StrictBool = Field(description="Specifies whether the network is verified.", alias="isVerified")
    name: StrictStr = Field(description="The name of the network.")
    origin_id: StrictInt = Field(description="The origin ID.", alias="originId")
    prefix_length: Annotated[int, Field(le=32, strict=True, ge=29)] = Field(description="The length of the prefix. Set a prefix length that is greater than 28 and less than 33.", alias="prefixLength")
    status: Annotated[str, Field(strict=True)] = Field(description="The status of the network.")
    __properties: ClassVar[List[str]] = ["createdAt", "ipAddress", "isDynamic", "isVerified", "name", "originId", "prefixLength", "status"]

    @field_validator('status')
    def status_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^(OPEN|CLOSED)$", value):
            raise ValueError(r"must validate the regular expression /^(OPEN|CLOSED)$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NetworkObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NetworkObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "createdAt": obj.get("createdAt"),
            "ipAddress": obj.get("ipAddress"),
            "isDynamic": obj.get("isDynamic"),
            "isVerified": obj.get("isVerified"),
            "name": obj.get("name"),
            "originId": obj.get("originId"),
            "prefixLength": obj.get("prefixLength"),
            "status": obj.get("status")
        })
        return _obj


