# Copyright 2025 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: v2.0.202510221109
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from secure_access.models.rule_action import RuleAction
from typing import Optional, Set
from typing_extensions import Self

class RulesResponseInner(BaseModel):
    """
    The core properties of the rule.
    """ # noqa: E501
    created_at: Optional[datetime] = Field(default=None, description="The date and time when the system created the access rule.", alias="createdAt")
    modified_at: Optional[datetime] = Field(default=None, description="The date and time when the system updated the access rule.", alias="modifiedAt")
    modified_by: Optional[StrictStr] = Field(default=None, description="A string that includes the organization ID and user ID for the account that modified the access rule.", alias="modifiedBy")
    organization_id: Optional[StrictInt] = Field(default=None, description="The ID of the organization.", alias="organizationId")
    rule_action: Optional[RuleAction] = Field(default=None, alias="ruleAction")
    rule_description: Optional[Annotated[str, Field(strict=True, max_length=256)]] = Field(default=None, description="The meaningful information about the rule. The description can have no more than 256 characters.", alias="ruleDescription")
    rule_id: StrictInt = Field(description="The ID of the rule.", alias="ruleId")
    rule_is_default: Optional[StrictBool] = Field(default=None, description="Specifies whether the rule is the default rule.", alias="ruleIsDefault")
    rule_is_enabled: Optional[StrictBool] = Field(default=None, description="Specifies whether the rule is enabled.", alias="ruleIsEnabled")
    rule_name: Optional[Annotated[str, Field(min_length=2, strict=True, max_length=50)]] = Field(default=None, description="A rule name is a sequence of 2–50 alphanumeric, hyphen, underscore, and space characters. A rule name is unique across all access rules in the organization's Access policy.", alias="ruleName")
    rule_priority: Optional[StrictInt] = Field(default=None, description="The positive integer that represents the priority of the rule. The priority is unique across all rules on the policy for the organization.", alias="rulePriority")
    __properties: ClassVar[List[str]] = ["createdAt", "modifiedAt", "modifiedBy", "organizationId", "ruleAction", "ruleDescription", "ruleId", "ruleIsDefault", "ruleIsEnabled", "ruleName", "rulePriority"]

    @field_validator('rule_name')
    def rule_name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-zA-Z0-9-_\s]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z0-9-_\s]+$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RulesResponseInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "created_at",
            "modified_at",
            "organization_id",
            "rule_id",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RulesResponseInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "createdAt": obj.get("createdAt"),
            "modifiedAt": obj.get("modifiedAt"),
            "modifiedBy": obj.get("modifiedBy"),
            "organizationId": obj.get("organizationId"),
            "ruleAction": obj.get("ruleAction"),
            "ruleDescription": obj.get("ruleDescription"),
            "ruleId": obj.get("ruleId"),
            "ruleIsDefault": obj.get("ruleIsDefault"),
            "ruleIsEnabled": obj.get("ruleIsEnabled"),
            "ruleName": obj.get("ruleName"),
            "rulePriority": obj.get("rulePriority")
        })
        return _obj


